## SRP150499

**paper:** [PMID: 36590595](https://pmc.ncbi.nlm.nih.gov/articles/PMC9797851/) - Rat and fish peripheral blood leukocytes respond distinctively to Anisakis pegreffii (Nematoda, Anisakidae) crude extract, 2022
* also [PMID: 30245697](https://pmc.ncbi.nlm.nih.gov/articles/PMC6137129/) - Molecular and Cellular Response to Experimental Anisakis pegreffii (Nematoda, Anisakidae) Third-Stage Larval Infection in Rats, 2018

**date, curator:** 2026-06-08, Sara Carsanaro

**notes**
* in the end, rejected everything except 2 libraries
    * rejected libraries infected with Anisakis pegreffii
    * rejected Anisakis pegreffii libraries
    * rejected PBLs because they were cell culture
* age is confusing - in SRA it says adult however they are 8 to 9 weeks old which is actually still juvenile stage, so i am annotating as juvenile

### annotation summary

In [20]:
anat_summary = library_to_add[['infoOrgan', 'anatId', 'anatName', 'anatAnnotationStatus']]
unique_anat = anat_summary.drop_duplicates()
display_df(unique_anat)

In [21]:
dev_summary = library_to_add[['infoStage', 'stageId', 'stageName', 'stageAnnotationStatus']]
unique_dev = dev_summary.drop_duplicates()
display_df(unique_dev)

### set variables, import packages, define functions

In [1]:
experiment_id = "SRP150499"

path_to_create_exp_script = "/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py" 
experiment_type = "bulk"

path_to_output_main = "/Users/scarsana/Desktop/git/expression-annotations/Notebooks/bulk/" 
path_to_output = "{}{}/".format(path_to_output_main, experiment_id)
library_path_from_script = "{}RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_path_from_script = "{}RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
library_to_add_path = "{}complete_RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_to_add_path = "{}complete_RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
script_file = "{}.ipynb".format(experiment_id)
commit_message_exp = '"adding annotated bulk experiment {}"'.format(experiment_id)
commit_message_py = '"adding annotation files for {} to notebook folder"'.format(experiment_id)


## to add to git
path_to_git_annotations = "/Users/scarsana/Desktop/git/expression-annotations/RNA_Seq/"
git_library_path = "{}RNASeqLibrary.tsv".format(path_to_git_annotations)
git_experiment_path = "{}RNASeqExperiment.tsv".format(path_to_git_annotations)

## validation
path_to_v_script = '/Users/scarsana/Desktop/git/continuous_integration/validate_annotations/validate_annotations.py'
path_to_rules = '/Users/scarsana/Desktop/git/continuous_integration/validate_annotations/rules/'
val_output = "{}{}/validation.tsv".format(path_to_output_main, experiment_id)

library_cols = ['#libraryId', 'experimentId', 'platform', 'SRSId', 'anatId', 'anatName', 'stageId', 'stageName', 'url_GSM', 'infoOrgan', 'infoStage', 'anatAnnotationStatus', 'anatBiologicalStatus', 'stageAnnotationStatus', 'sex', 'strain', 'genotype', 'speciesId', 'protocol', 'protocolType', 'RNASelection', 'globin_reduction', 'replicate', 'lib_name', 'sampleName', 'sampleAge_value', 'sampleAge_unit', 'PATOid', 'PATOname','EFOid', 'EFOname','comment', 'condition', 'physiologicalStatus', 'annotatorId', 'lastModificationDate']

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import os
import csv

# displays df with the scrollbar next to the DataFrame
def display_df(df):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    display(HTML("<div style='height: 300px; overflow: auto; width: fit-content'>" +
        df.style.to_html(index=False) + "</div>"))

# function that compares two columns in a dataframe and tells you which ones are not equal (case insensitive)
def compare_columns(df, col1, col2, return_col):
    compare_return = df[col1].str.lower() != df[col2].str.lower()  
    df.loc[compare_return, return_col] 
    if not any(compare_return):
        print("The two columns are equal (case insensitive)")
    else:
        print("The following rows are not equal: ")
        print(df.loc[compare_return, return_col])

# fixes formatting of file to match libreoffice settings/historic file format
def update_format(path):
    with open(path, 'r') as file:
        filedata = file.read()
    # Replace the target string
    filedata = filedata.replace("\t\"\"", "\t")
    # Write the file out again
    with open(path, 'w') as file:
        file.write(filedata)

# checks for duplicate values in a specific column and prints those values + the corresponding library id
def dup_check(df, column):
    duplicateCheck = df.duplicated(subset=[column], keep=False)
    duplicateCheck.sort_values(inplace=True)
    if duplicateCheck.unique().any() == False:
        print("no duplicate values in " + column)
    elif duplicateCheck.unique().any() == True and column != '#libraryId':
        dups = df[duplicateCheck].loc[:,['#libraryId', column]]
        df_dups = pd.DataFrame(dups)
        df_dups.sort_values(inplace=True, by=column)
        print(df_dups)
    elif duplicateCheck.unique().any() == True and column == '#libraryId':
        print(df[duplicateCheck].loc[:,['#libraryId']])

# prints all unique values in a specific column
def unique_sorted(df, column):
    unique = df[column].unique()
    unique.sort()
    print(unique)

### script

In [3]:
! python3 $path_to_create_exp_script $experiment_id $path_to_output $experiment_type

/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:120: SyntaxWarning: invalid escape sequence '\('
  all_protoc = [w.replace('(', '\(') for w in all_protoc]
/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:121: SyntaxWarning: invalid escape sequence '\)'
  all_protoc = [w.replace(')', '\)') for w in all_protoc]
Be patient, it may take a few minutes.
 20%|████████▍                                  | 12/61 [00:13<00:54,  1.12s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:01:30 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX13579420&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:01:30 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX13579420 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 26%|███████████▎                               | 16/61 [00:18<00:53,  1.18s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:01:36 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX10250741&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:01:35 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX10250741 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 48%|████████████████████▍                      | 29/61 [00:33<00:31,  1.03it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:01:51 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX10250728&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:01:50 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX10250728 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 64%|███████████████████████████▍               | 39/61 [00:45<00:20,  1.05it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:02:02 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX10250718&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:02:02 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX10250718 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 66%|████████████████████████████▏              | 40/61 [00:47<00:31,  1.48s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:02:05 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX10250717&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:02:04 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX10250717 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 82%|███████████████████████████████████▏       | 50/61 [01:03<00:15,  1.38s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:02:20 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX4213815&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:02:20 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX4213815 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 85%|████████████████████████████████████▋      | 52/61 [01:06<00:13,  1.55s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:02:24 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX4213813&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:02:23 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX4213813 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
100%|███████████████████████████████████████████| 61/61 [01:18<00:00,  1.28s/it]
 WARNING:  FAILURE ( Mon Jun  8 14:02:38 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ elink.fcgi -id 18868345,18868344,18868343,18868342,18868341,18868340,18868339,18868338,18868337,18868336,18868335,18868334,18868333,18868332,13378319,13378318,13378317,13378316,13378315,13378314,13378313,13378312,13378311,13378310,13378309,13378308,13378307,13378306,13378305,13378304,13378303,13378302,13378301,13378300,13378299,13378298,13378297,13378296,13378295,13378294,13378293,13378292,13378291,13378290,13378289,5700764,5700763,5700762,5700761,5700760,5700759,5700758,5700757,5700756,5700755,5700754,5700753,5700752,5700751,5700750,5700749 -WebEnv MCID_6a26af5b5089de49c806edd9 -dbfrom sra -db biosample -cmd neighbor_history -linkname sra_biosample -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Error calling ExLink server.</ERROR>
SECOND ATTEMPT
 WARNING:  FAILURE ( Mon Jun  8 14:02:44 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ elink.fcgi -id 18868345,18868344,18868343,18868342,18868341,18868340,18868339,18868338,18868337,18868336,18868335,18868334,18868333,18868332,13378319,13378318,13378317,13378316,13378315,13378314,13378313,13378312,13378311,13378310,13378309,13378308,13378307,13378306,13378305,13378304,13378303,13378302,13378301,13378300,13378299,13378298,13378297,13378296,13378295,13378294,13378293,13378292,13378291,13378290,13378289,5700764,5700763,5700762,5700761,5700760,5700759,5700758,5700757,5700756,5700755,5700754,5700753,5700752,5700751,5700750,5700749 -WebEnv MCID_6a26af5b5089de49c806edd9 -dbfrom sra -db biosample -cmd neighbor_history -linkname sra_biosample -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Error calling ExLink server.</ERROR>
LAST ATTEMPT
 ERROR:  FAILURE ( Mon Jun  8 14:02:52 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ elink.fcgi -id 18868345,18868344,18868343,18868342,18868341,18868340,18868339,18868338,18868337,18868336,18868335,18868334,18868333,18868332,13378319,13378318,13378317,13378316,13378315,13378314,13378313,13378312,13378311,13378310,13378309,13378308,13378307,13378306,13378305,13378304,13378303,13378302,13378301,13378300,13378299,13378298,13378297,13378296,13378295,13378294,13378293,13378292,13378291,13378290,13378289,5700764,5700763,5700762,5700761,5700760,5700759,5700758,5700757,5700756,5700755,5700754,5700753,5700752,5700751,5700750,5700749 -WebEnv MCID_6a26af5b5089de49c806edd9 -dbfrom sra -db biosample -cmd neighbor_history -linkname sra_biosample -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eLinkResult>
<eLinkResult>
  <LinkSet>
    <DbFrom>sra</DbFrom>
    <IdList>
      <Id>18868345</Id>
      <Id>18868344</Id>
      <Id>18868343</Id>
      <Id>18868342</Id>
      <Id>18868341</Id>
      <Id>18868340</Id>
      <Id>18868339</Id>
      <Id>18868338</Id>
      <Id>18868337</Id>
      <Id>18868336</Id>
      <Id>18868335</Id>
      <Id>18868334</Id>
      <Id>18868333</Id>
      <Id>18868332</Id>
      <Id>13378319</Id>
      <Id>13378318</Id>
      <Id>13378317</Id>
      <Id>13378316</Id>
      <Id>13378315</Id>
      <Id>13378314</Id>
      <Id>13378313</Id>
      <Id>13378312</Id>
      <Id>13378311</Id>
      <Id>13378310</Id>
      <Id>13378309</Id>
      <Id>13378308</Id>
      <Id>13378307</Id>
      <Id>13378306</Id>
      <Id>13378305</Id>
      <Id>13378304</Id>
      <Id>13378303</Id>
      <Id>13378302</Id>
      <Id>13378301</Id>
      <Id>13378300</Id>
      <Id>13378299</Id>
      <Id>13378298</Id>
      <Id>13378297</Id>
      <Id>13378296</Id>
      <Id>13378295</Id>
      <Id>13378294</Id>
      <Id>13378293</Id>
      <Id>13378292</Id>
      <Id>13378291</Id>
      <Id>13378290</Id>
      <Id>13378289</Id>
      <Id>5700764</Id>
      <Id>5700763</Id>
      <Id>5700762</Id>
      <Id>5700761</Id>
      <Id>5700760</Id>
      <Id>5700759</Id>
      <Id>5700758</Id>
      <Id>5700757</Id>
      <Id>5700756</Id>
      <Id>5700755</Id>
      <Id>5700754</Id>
      <Id>5700753</Id>
      <Id>5700752</Id>
      <Id>5700751</Id>
      <Id>5700750</Id>
      <Id>5700749</Id>
    </IdList>
    <LinkSetDbHistory>
      <DbTo>biosample</DbTo>
      <LinkName>sra_biosample</LinkName>
      <ERROR>Error calling ExLink server.</ERROR>
    </LinkSetDbHistory>
    <WebEnv>MCID_6a26af5b5089de49c806edd9</WebEnv>
  </LinkSet>
</eLinkResult>
QUERY FAILURE
61 samples dont have attributes, try to find them somewhere else
  2%|▋                                           | 1/61 [00:02<02:57,  2.95s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:03:14 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=biosample&term=SAMN24563496%20%5BACCN%5D&retmax=10000>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:03:14 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563496 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Invalid uid SAMN24563496 at position= 0</ERROR>
SECOND ATTEMPT
 WARNING:  FAILURE ( Mon Jun  8 14:03:16 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563496 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Invalid uid SAMN24563496 at position= 0</ERROR>
LAST ATTEMPT
 ERROR:  FAILURE ( Mon Jun  8 14:03:18 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563496 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult>
<eSummaryResult>
  <ERROR>Invalid uid SAMN24563496 at position= 0</ERROR>
  <DocumentSummarySet status="OK"/>
</eSummaryResult>
QUERY FAILURE
 10%|████▎                                       | 6/61 [00:20<02:34,  2.82s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:03:32 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi -d db=biosample&id=24563512&version=2.0&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:03:32 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id 24563512 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 11%|█████                                       | 7/61 [00:24<02:49,  3.15s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:03:35 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=biosample&term=SAMN24563498%20%5BACCN%5D&retmax=10000>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:03:35 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563498 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Invalid uid SAMN24563498 at position= 0</ERROR>
SECOND ATTEMPT
curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:03:38 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi -d db=biosample&id=SAMN24563498&version=2.0&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:03:37 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563498 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
 ERROR:  FAILURE ( Mon Jun  8 14:03:39 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN24563498 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult>
<eSummaryResult>
  <ERROR>Invalid uid SAMN24563498 at position= 0</ERROR>
  <DocumentSummarySet status="OK"/>
</eSummaryResult>
QUERY FAILURE
 98%|██████████████████████████████████████████▎| 60/61 [02:39<00:02,  2.38s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Jun  8 14:05:50 CEST 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=biosample&term=SAMN09425531%20%5BACCN%5D&retmax=10000>78
HTTP/1.0 429 Too Many Requests
 WARNING:  FAILURE ( Mon Jun  8 14:05:50 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN09425531 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Invalid uid SAMN09425531 at position= 0</ERROR>
SECOND ATTEMPT
 WARNING:  FAILURE ( Mon Jun  8 14:05:52 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN09425531 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Invalid uid SAMN09425531 at position= 0</ERROR>
LAST ATTEMPT
 ERROR:  FAILURE ( Mon Jun  8 14:05:54 CEST 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ esummary.fcgi -db biosample -id SAMN09425531 -version 2.0 -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE eSummaryResult>
<eSummaryResult>
  <ERROR>Invalid uid SAMN09425531 at position= 0</ERROR>
  <DocumentSummarySet status="OK"/>
</eSummaryResult>
QUERY FAILURE
100%|███████████████████████████████████████████| 61/61 [02:46<00:00,  2.74s/it]
3 samples dont have attributes

### library annnotations

In [4]:
library = pd.read_csv(library_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(library)

#### anatomical entity
* [uberon ols](https://www.ebi.ac.uk/ols4/ontologies/uberon)

In [5]:
unique_sorted(library, "infoOrgan")

['muscle tissues' 'stomach tissues']

#### stage
- [species specific developmental ontologies](https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/ontology/components)

In [6]:
unique_sorted(library, "infoStage")

['around 8 to 9 weeks old']

#### sex, strain, genotype, speciesId
- uniprot [strain list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/strains)
- uniprot [species list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/speclist)
- bgee [strain mapping](https://gitlab.sib.swiss/Bgee/expression-annotations/-/tree/develop/Strains?ref_type=heads)

In [7]:
#library.loc[:,'sex'] = ''
#library.loc[library["sex"] == "male", "sex"] = "M"
#library.loc[library["sex"] == "female", "sex"] = "F"

#library.loc[:,'strain'] = ''

#library.loc[:,'genotype'] = ''

#library.loc[:,'speciesId'] = ''

# view
display_df(library)

#### protocol
see [bulk kits](https://gitlab.sib.swiss/Bgee/scRNA-Seq/-/blob/main/scripts/bulk_kits.csv) for some common protocols

In [8]:
# making these variables because we use them again in the experiment file
my_protocol = 'TruSeq Stranded mRNA'
# full_length or 3'
my_protocolType = 'full_length'

library.loc[:,'protocol'] = my_protocol
library.loc[:,'protocolType'] = my_protocolType
# polyA, ribo-minus, miRNA, lncRNA, circRNA
library.loc[:,'RNASelection'] = 'polyA'

# view
display_df(library)

#### globin, replicates

In [9]:
# check for duplicate SRSId values
dup_check(library, "SRSId")

no duplicate values in SRSId

In [ ]:
#library.loc[:,'globin_reduction'] = 'Y'

# replicates
#library.loc[library["#libraryId"] == "old", "replicate"] = "1"
#library.loc[library["#libraryId"].isin(["one", "two"]), "replicate"] = "1"

# view
display_df(library)

#### sample age, pato, physiological status
* [PATO](https://www.ebi.ac.uk/ols4/ontologies/pato)
* [EFO](https://www.ebi.ac.uk/ols4/ontologies/efo)

In [ ]:
#library.loc[:,'sampleAge_value'] = ''
#library.loc[:,'sampleAge_unit'] = ''

# ex. castrated male
#library.loc[:,'PATOid'] = ''
#library.loc[:,'PATOname'] = ''

# ex. castrated, pregnant, pre-smoltification, post-smoltification, laying eggs
#library.loc[:,'physiologicalStatus'] = ''

# ex. left, right
#library.loc[:,'EFOid'] = ''
#library.loc[:,'EFOname'] = ''

# view
display_df(library)

#### condition

In [ ]:
# ex. control, diet, light, reproductive capacity, time post mortem, time post feeding, 
# exercise details, menstruation, personality, litter size 
#library.loc[library["condition"] == "old", "condition"] = "new"

# view
display_df(library)

#### annotator id, last modification date

In [10]:
library.loc[:,'annotatorId'] = 'SAC'
library.loc[:,'lastModificationDate'] = '2026-06-08'

# view
display_df(library)

#### comments

In [ ]:
#library.loc[:,'comment'] = ''

#### save complete file with correct columns

In [11]:
library_file_complete = library[library_cols]
library_file_complete.to_csv(library_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

# view
display_df(library_file_complete)

### experiment annotations

In [12]:
experiment = pd.read_csv(experiment_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(experiment)

#### experiment and protocol details

In [13]:
# this will give you the number of rows in the complete library file 
# this should be the number of annotated libraries
ann_lib = len(library_file_complete.index)
len(library_file_complete.index)

2

In [14]:
# partial or total
experiment.loc[:,'experimentStatus'] = 'partial'
# Bgee 1K
experiment.loc[:,'projectTags'] = 'Bgee 1K' 
# see above cell, also can add as free text
experiment.loc[:,'numberOfAnnotatedLibraries'] = ann_lib

# these variables should already exist from above but if not can just add as free text
experiment.loc[:,'protocol'] = my_protocol
experiment.loc[:,'protocolType'] = my_protocolType

display_df(experiment)

#### paper and xrefs

In [15]:
#experiment.loc[:,'GSE'] = ''
#experiment.loc[:,'Bioproject'] = '' 
experiment.loc[:,'PMID'] = '30245697'
experiment.loc[:,'reference_url'] = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6137129/'
experiment.loc[:,'DOI'] = '10.3389/fimmu.2018.02055'
experiment.loc[:,'xrefs'] = '36590595[PMID],34186188[PMID]'

display_df(experiment)

#### comments

In [16]:
experiment.loc[:,'comment'] = 'rejected infected libraries and cell culture'

display_df(experiment)

#### save complete file

In [17]:
experiment.to_csv(experiment_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

### QA time

In [18]:
library_to_add = pd.read_csv(library_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
experiment_to_add = pd.read_csv(experiment_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

In [19]:
! python3 $path_to_v_script --bulk-exp $experiment_to_add_path --bulk-lib $library_to_add_path --rules-dir $path_to_rules --out $val_output --strict

Total issues: 0
Errors: 0
Warnings: 0
Top codes:

#### check columns match

In [22]:
# pull from git and pull in library/experiment file
! git pull
git_library = pd.read_csv(git_library_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
git_experiment = pd.read_csv(git_experiment_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

# library file
if set(library_to_add.columns) == set(git_library.columns):
    print('The columns in the library file match')
else:
    print('The columns in the library file DO NOT MATCH')

# experiment file
if set(experiment_to_add.columns) == set(git_experiment.columns):
    print('The columns in the experiment file match')
else:
    print('The columns in the experiment file DO NOT MATCH')


# maybe to make this something more like "COLUMNS GOOD - LIBRARY" and "COLUMNS BAD - EXPERIMENT"

Already up to date.
The columns in the library file match
The columns in the experiment file match

#### view files

In [23]:
library_git_plus_new = pd.concat([git_library, library_to_add], ignore_index = True, sort = False)
old_length = git_library.shape[0]
start = old_length - 2
end = old_length + 5
view_lib = library_git_plus_new.iloc[start:end]
view_lib

,#libraryId,experimentId,platform,SRSId,anatId,anatName,stageId,stageName,url_GSM,infoOrgan,infoStage,anatAnnotationStatus,anatBiologicalStatus,stageAnnotationStatus,sex,strain,genotype,speciesId,protocol,protocolType,RNASelection,globin_reduction,replicate,lib_name,sampleName,sampleAge_value,sampleAge_unit,PATOid,PATOname,EFOid,EFOname,comment,condition,physiologicalStatus,annotatorId,lastModificationDate
65343,SRX20810529,SRP446379,Illumina NovaSeq 6000,SRS18093993,UBERON:0001898,hypothalamus,MmusDv:0000154,8-week-old stage,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,hypothalamus,8 weeks,perfect match,full sampling,,M,C57BL/6J,,10090,NEBNext Ultra Directional RNA Library Prep Kit,full_length,ribo-minus,,,"hypothalamus, both, chow, 2",SAMN36028227,,,,,,,"PMID:38184639, C57BL/6 J male mice (8 weeks ol...",chow diet,,ANN,2026-06-08
65344,SRX20810528,SRP446379,Illumina NovaSeq 6000,SRS18093992,UBERON:0001898,hypothalamus,MmusDv:0000154,8-week-old stage,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,hypothalamus,8 weeks,perfect match,full sampling,,M,C57BL/6J,,10090,NEBNext Ultra Directional RNA Library Prep Kit,full_length,ribo-minus,,,"hypothalamus, both, chow, 1",SAMN36028228,,,,,,,"PMID:38184639, C57BL/6 J male mice (8 weeks ol...",chow diet,,ANN,2026-06-08
65345,SRX4213810,SRP150499,NextSeq 500,SRS3416470,UBERON:0000945,stomach,RnorDv:0000058,juvenile stage,,stomach tissues,around 8 to 9 weeks old,perfect match,not documented,other,M,Sprague-Dawley,,10116,TruSeq Stranded mRNA,full_length,polyA,,,K0_S,SAMN09425536,,,,,,,this is actually 4 different parts of the stom...,Non-infected,,SAC,2026-06-08
65346,SRX4213815,SRP150499,NextSeq 500,SRS3416475,UBERON:0002385,muscle tissue,RnorDv:0000058,juvenile stage,,muscle tissues,around 8 to 9 weeks old,perfect match,not documented,other,M,Sprague-Dawley,,10116,TruSeq Stranded mRNA,full_length,polyA,,,K0_M,SAMN09425527,,,,,,,PMID: 30245697,Non-infected,,SAC,2026-06-08

In [24]:
experiment_git_plus_new = pd.concat([git_experiment, experiment_to_add], ignore_index = True, sort = False)
experiment_git_plus_new.tail(n=3)

,#experimentId,experimentName,experimentDescription,experimentSource,experimentStatus,projectTags,numberOfAnnotatedLibraries,protocol,protocolType,GSE,Bioproject,PMID,reference_url,DOI,xrefs,comment
1245,SRP119034,Consistent inverse correlation between DNA met...,Background: DNA methylation is one of the main...,SRA,partial,Bgee 1K,10,TruSeq RNA Sample Preparation Kit,full_length,GSE104366,PRJNA412454,29958539,https://pmc.ncbi.nlm.nih.gov/articles/PMC6025724/,10.1186/s13072-018-0205-1,35741749[PMID],partial because bisulfite seq libaries were re...
1246,SRP446379,An RNA-seq atlas of mouse brain areas during f...,Mammalian energy homeostasis is regulated by t...,SRA,total,,185,NEBNext Ultra Directional RNA Library Prep Kit,full_length,GSE236077,PRJNA988797,38184639,https://pmc.ncbi.nlm.nih.gov/articles/PMC10771...,10.1038/s41597-023-02888-4,,[Bgee curator notes: mouse fasted max 24 hours...
1247,SRP150499,Rattus norvegicus and Anisakis pegreffii RNAse...,Considered as one of the most significant emer...,SRA,partial,Bgee 1K,2,TruSeq Stranded mRNA,full_length,,PRJNA475982,30245697,https://pmc.ncbi.nlm.nih.gov/articles/PMC6137129/,10.3389/fimmu.2018.02055,"36590595[PMID],34186188[PMID]",rejected infected libraries and cell culture

### add annotations to git

In [25]:
! git pull

Already up to date.

In [26]:
library_git_plus_new.to_csv(git_library_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
experiment_git_plus_new.to_csv(git_experiment_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
update_format(git_library_path)
update_format(git_experiment_path)

In [ ]:
! git status

In [27]:
! git add $git_experiment_path $git_library_path

In [28]:
! git commit -m $commit_message_exp

[develop 144109e] adding annotated bulk experiment SRP150499
 2 files changed, 3 insertions(+)

In [29]:
! git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.82 KiB | 721.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.sib.swiss/Bgee/expression-annotations/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.sib.swiss/Bgee/expression-annotations.git/
   5cdd15c..144109e  develop -> develop

### add annotation folder and script to git

In [ ]:
! git pull

1. run first two cells (annotation summary)
2. export as html

In [ ]:
! git add $path_to_output

In [ ]:
! git commit -m $commit_message_py

In [ ]:
! git push