## SRP115009

**paper:** [PMID: 37183864](https://pmc.ncbi.nlm.nih.gov/articles/PMC10210625/) - A New Chromosome-Assigned Mongolian Gerbil Genome Allows Characterization of Complete Centromeres and a Fully Heterochromatic Chromosome, 2023

**date, curator:** 2026-02-02, Sara Carsanaro

**notes**
* majority of these librares are no RNA-seq
* paper says these are kidney and testis from three individuals, SRA says liver, kidney, testis
* not a lot of info in supplementary methods about RNA-seq, but seems pretty standard overall
* some of the samples are 3.5 months, others are 6. all are sexually mature adults, Mongolian Gerbil sexual maturity occurs at 36 days days for males, 43 days for females. actually, we can confidently annotate as prime adult stage

### annotation summary

In [21]:
anat_summary = library_to_add[['infoOrgan', 'anatId', 'anatName', 'anatAnnotationStatus']]
unique_anat = anat_summary.drop_duplicates()
display_df(unique_anat)

In [22]:
dev_summary = library_to_add[['infoStage', 'stageId', 'stageName', 'stageAnnotationStatus']]
unique_dev = dev_summary.drop_duplicates()
display_df(unique_dev)

### set variables, import packages, define functions

In [1]:
experiment_id = "SRP115009"

path_to_create_exp_script = "/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py" 
experiment_type = "bulk"

path_to_output_main = "/Users/scarsana/Desktop/git/expression-annotations/Notebooks/bulk/" 
path_to_output = "{}{}/".format(path_to_output_main, experiment_id)
library_path_from_script = "{}RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_path_from_script = "{}RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
library_to_add_path = "{}complete_RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_to_add_path = "{}complete_RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
script_file = "{}.ipynb".format(experiment_id)
commit_message_exp = '"adding annotated bulk experiment {}"'.format(experiment_id)
commit_message_py = '"adding annotation files for {} to notebook folder"'.format(experiment_id)


## to add to git
path_to_git_annotations = "/Users/scarsana/Desktop/git/expression-annotations/RNA_Seq/"
git_library_path = "{}RNASeqLibrary.tsv".format(path_to_git_annotations)
git_experiment_path = "{}RNASeqExperiment.tsv".format(path_to_git_annotations)

library_cols = ['#libraryId', 'experimentId', 'platform', 'SRSId', 'anatId', 'anatName', 'stageId', 'stageName', 'url_GSM', 'infoOrgan', 'infoStage', 'anatAnnotationStatus', 'anatBiologicalStatus', 'stageAnnotationStatus', 'sex', 'strain', 'genotype', 'speciesId', 'protocol', 'protocolType', 'RNASelection', 'globin_reduction', 'replicate', 'lib_name', 'sampleName', 'sampleAge_value', 'sampleAge_unit', 'PATOid', 'PATOname','EFOid', 'EFOname','comment', 'condition', 'physiologicalStatus', 'annotatorId', 'lastModificationDate']

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import os
import csv

# displays df with the scrollbar next to the DataFrame
def display_df(df):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    display(HTML("<div style='height: 300px; overflow: auto; width: fit-content'>" +
        df.style.to_html(index=False) + "</div>"))

# function that compares two columns in a dataframe and tells you which ones are not equal (case insensitive)
def compare_columns(df, col1, col2, return_col):
    compare_return = df[col1].str.lower() != df[col2].str.lower()  
    df.loc[compare_return, return_col] 
    if not any(compare_return):
        print("The two columns are equal (case insensitive)")
    else:
        print("The following rows are not equal: ")
        print(df.loc[compare_return, return_col])

# fixes formatting of file to match libreoffice settings/historic file format
def update_format(path):
    with open(path, 'r') as file:
        filedata = file.read()
    # Replace the target string
    filedata = filedata.replace("\t\"\"", "\t")
    # Write the file out again
    with open(path, 'w') as file:
        file.write(filedata)

# checks for duplicate values in a specific column and prints those values + the corresponding library id
def dup_check(df, column):
    duplicateCheck = df.duplicated(subset=[column], keep=False)
    duplicateCheck.sort_values(inplace=True)
    if duplicateCheck.unique().any() == False:
        print("no duplicate values in " + column)
    elif duplicateCheck.unique().any() == True and column != '#libraryId':
        dups = df[duplicateCheck].loc[:,['#libraryId', column]]
        df_dups = pd.DataFrame(dups)
        df_dups.sort_values(inplace=True, by=column)
        print(df_dups)
    elif duplicateCheck.unique().any() == True and column == '#libraryId':
        print(df[duplicateCheck].loc[:,['#libraryId']])

# prints all unique values in a specific column
def unique_sorted(df, column):
    unique = df[column].unique()
    unique.sort()
    print(unique)

### script

In [4]:
! python3 $path_to_create_exp_script $experiment_id $path_to_output $experiment_type

/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:120: SyntaxWarning: invalid escape sequence '\('
  all_protoc = [w.replace('(', '\(') for w in all_protoc]
/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:121: SyntaxWarning: invalid escape sequence '\)'
  all_protoc = [w.replace(')', '\)') for w in all_protoc]
Be patient, it may take a few minutes.
curl: (28) SSL connection timeout
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:30:03 CET 2026 ) with: 28>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=bioproject&term=PRJNA397533%20%5BPRJA%5D&retmax=10000>78
curl: (28) SSL connection timeout
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:30:24 CET 2026 ) with: 28>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=bioproject&id=PRJNA397533&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
 WARNING:  FAILURE ( Mon Feb  2 16:30:23 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db bioproject -id PRJNA397533 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
  0%|                                                   | 0/197 [00:00<?, ?it/s]curl: (35) Recv failure: Connection reset by peer
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:31:12 CET 2026 ) with: 35>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14497519&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
 WARNING:  FAILURE ( Mon Feb  2 16:31:12 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14497519 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (28) SSL connection timeout
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:31:18 CET 2026 ) with: 28>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14497519&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
 WARNING:  FAILURE ( Mon Feb  2 16:31:18 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14497519 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
  2%|▋                                          | 3/197 [00:50<44:39, 13.81s/it]curl: (35) Recv failure: Connection reset by peer
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:32:04 CET 2026 ) with: 35>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14497516&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
 WARNING:  FAILURE ( Mon Feb  2 16:32:03 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14497516 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 16%|██████▌                                   | 31/197 [01:42<02:34,  1.07it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:32:52 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646493&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:32:52 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646493 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 18%|███████▍                                  | 35/197 [01:47<03:00,  1.11s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:32:58 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646489&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:32:57 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646489 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 19%|███████▉                                  | 37/197 [01:51<03:45,  1.41s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:01 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646487&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:01 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646487 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 20%|████████▎                                 | 39/197 [01:55<04:08,  1.58s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:05 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646485&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:05 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646485 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 23%|█████████▊                                | 46/197 [02:03<02:36,  1.03s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:13 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646478&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:13 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646478 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 24%|██████████                                | 47/197 [02:06<03:53,  1.55s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:16 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646477&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:16 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646477 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 29%|████████████▏                             | 57/197 [02:17<02:12,  1.05it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:27 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646467&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:27 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646467 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 33%|█████████████▊                            | 65/197 [02:27<02:28,  1.13s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:38 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646459&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:37 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646459 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 37%|███████████████▎                          | 72/197 [02:36<02:15,  1.09s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:47 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646452&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:46 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646452 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 38%|███████████████▊                          | 74/197 [02:40<02:52,  1.40s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:50 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646450&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:50 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646450 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 38%|███████████████▉                          | 75/197 [02:43<03:44,  1.84s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:53 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646449&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:53 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646449 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 40%|████████████████▊                         | 79/197 [02:48<02:37,  1.33s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:33:59 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646445&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:33:58 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646445 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 43%|█████████████████▉                        | 84/197 [02:55<02:13,  1.18s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:34:06 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646440&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:34:05 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646440 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 50%|████████████████████▉                     | 98/197 [03:10<01:34,  1.05it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:34:21 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646426&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:34:20 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646426 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 54%|██████████████████████                   | 106/197 [03:22<01:43,  1.14s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:34:32 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646418&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:34:32 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646418 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 78%|███████████████████████████████▊         | 153/197 [04:10<00:41,  1.06it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:35:21 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646371&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:35:20 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646371 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 80%|████████████████████████████████▉        | 158/197 [04:17<00:41,  1.07s/it]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:35:27 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX5646366&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:35:27 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX5646366 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 95%|██████████████████████████████████████▉  | 187/197 [04:46<00:09,  1.01it/s]curl: (22) The requested URL returned error: 429
>78 ERROR: >78 curl command failed ( Mon Feb  2 16:35:57 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX3070235&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 429 Too Many Requests
 WARNING:  FAILURE ( Mon Feb  2 16:35:56 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX3070235 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
100%|█████████████████████████████████████████| 197/197 [04:57<00:00,  1.51s/it]
0 samples dont have attributes, try to find them somewhere else
0it [00:00, ?it/s]
0 samples dont have attributes
Fetching RunIds and ReadHashes for each library...can take several minutes
⚠️ Failed to fetch ReadHash for SRX14497507: Command 'esearch -db sra -query SRX14497507 | efetch -format runinfo' returned non-zero exit status 1.

### library annnotations

In [5]:
library = pd.read_csv(library_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(library)

#### anatomical entity
* [uberon ols](https://www.ebi.ac.uk/ols4/ontologies/uberon)

In [6]:
unique_sorted(library, "infoOrgan")

['liver, kidney, testis']

In [7]:

# all
library.loc[:,'anatId'] = 'UBERON:0000468'
library.loc[:,'anatName'] = 'multicellular organism'
# perfect match, missing child term, other
library.loc[:,'anatAnnotationStatus'] = 'other'
# partial sampling, full sampling, not documented
library.loc[:,'anatBiologicalStatus'] = 'not documented'


# view
display_df(library)

#### stage
- [species specific developmental ontologies](https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/ontology/components)

In [8]:
unique_sorted(library, "infoStage")

['3.5 months' '6 months']

In [9]:
# all
library.loc[:,'stageId'] = 'UBERON:0018241'
library.loc[:,'stageName'] = 'prime adult stage'
# perfect match, missing child term, other
library.loc[:,'stageAnnotationStatus'] = 'other'


# view
display_df(library)

#### sex, strain, genotype, speciesId
- uniprot [strain list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/strains)
- uniprot [species list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/speclist)
- bgee [strain mapping](https://gitlab.sib.swiss/Bgee/expression-annotations/-/tree/develop/Strains?ref_type=heads)

In [ ]:
#library.loc[:,'sex'] = 'M'
#library.loc[library["sex"] == "male", "sex"] = "M"
#library.loc[library["sex"] == "female", "sex"] = "F"

#library.loc[:,'strain'] = ''

#library.loc[:,'genotype'] = ''

#library.loc[:,'speciesId'] = ''

# view
display_df(library)

#### protocol
see [bulk kits](https://gitlab.sib.swiss/Bgee/scRNA-Seq/-/blob/main/scripts/bulk_kits.csv) for some common protocols

In [10]:
# making these variables because we use them again in the experiment file
#my_protocol = ''
# full_length or 3'
#my_protocolType = ''

#library.loc[:,'protocol'] = my_protocol
#library.loc[:,'protocolType'] = my_protocolType
# polyA, ribo-minus, miRNA, lncRNA, circRNA
library.loc[:,'RNASelection'] = 'polyA'

# view
display_df(library)

#### globin, replicates

In [11]:
# check for duplicate SRSId values
dup_check(library, "SRSId")

    #libraryId        SRSId
0  SRX14497495  SRS12295831
1  SRX14497506  SRS12295831
2  SRX14497513  SRS12295833
3  SRX14497514  SRS12295833
4  SRX14497518  SRS12295835
5  SRX14497519  SRS12295835

In [ ]:
#library.loc[:,'globin_reduction'] = 'Y'

# replicates
#library.loc[library["#libraryId"] == "old", "replicate"] = "1"
#library.loc[library["#libraryId"].isin(["one", "two"]), "replicate"] = "1"

# view
display_df(library)

#### sample age, pato, physiological status
* [PATO](https://www.ebi.ac.uk/ols4/ontologies/pato)
* [EFO](https://www.ebi.ac.uk/ols4/ontologies/efo)

In [ ]:
#library.loc[:,'sampleAge_value'] = ''
#library.loc[:,'sampleAge_unit'] = ''

# ex. castrated male
#library.loc[:,'PATOid'] = ''
#library.loc[:,'PATOname'] = ''

# ex. castrated, pregnant, pre-smoltification, post-smoltification, laying eggs
#library.loc[:,'physiologicalStatus'] = ''

# ex. left, right
#library.loc[:,'EFOid'] = ''
#library.loc[:,'EFOname'] = ''

# view
display_df(library)

#### condition

In [ ]:
# ex. control, diet, light, reproductive capacity, time post mortem, time post feeding, 
# exercise details, menstruation, personality, litter size 
#library.loc[library["condition"] == "old", "condition"] = "new"

# view
display_df(library)

#### annotator id, last modification date

In [12]:
library.loc[:,'annotatorId'] = 'SAC'
library.loc[:,'lastModificationDate'] = '2026-02-02'

# view
display_df(library)

#### comments

In [ ]:
#library.loc[:,'comment'] = ''

#### save complete file with correct columns

In [13]:
library_file_complete = library[library_cols]
library_file_complete.to_csv(library_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

# view
display_df(library_file_complete)

### experiment annotations

In [14]:
experiment = pd.read_csv(experiment_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(experiment)

#### experiment and protocol details

In [15]:
# this will give you the number of rows in the complete library file 
# this should be the number of annotated libraries
ann_lib = len(library_file_complete.index)
len(library_file_complete.index)

6

In [16]:
# partial or total
experiment.loc[:,'experimentStatus'] = 'partial'
# Bgee 1K
experiment.loc[:,'projectTags'] = 'Bgee 1K' 
# see above cell, also can add as free text
experiment.loc[:,'numberOfAnnotatedLibraries'] = ann_lib

# these variables should already exist from above but if not can just add as free text
#experiment.loc[:,'protocol'] = my_protocol
#experiment.loc[:,'protocolType'] = my_protocolType

display_df(experiment)

#### paper and xrefs

In [17]:
#experiment.loc[:,'GSE'] = ''
#experiment.loc[:,'Bioproject'] = '' 
experiment.loc[:,'PMID'] = '37183864'
experiment.loc[:,'reference_url'] = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10210625/'
experiment.loc[:,'DOI'] = '10.1093/molbev/msad115'
#experiment.loc[:,'xrefs'] = ''

display_df(experiment)

#### comments

In [18]:
experiment.loc[:,'comment'] = 'partial because majority of libraries are not RNA-seq, rejected. mixed tissues, to review after group meeting'

display_df(experiment)

#### save complete file

In [19]:
experiment.to_csv(experiment_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

### QA time

In [20]:
library_to_add = pd.read_csv(library_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
experiment_to_add = pd.read_csv(experiment_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

#### to add things here

#### check columns match

In [23]:
# pull from git and pull in library/experiment file
! git pull
git_library = pd.read_csv(git_library_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
git_experiment = pd.read_csv(git_experiment_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

# library file
if set(library_to_add.columns) == set(git_library.columns):
    print('The columns in the library file match')
else:
    print('The columns in the library file DO NOT MATCH')

# experiment file
if set(experiment_to_add.columns) == set(git_experiment.columns):
    print('The columns in the experiment file match')
else:
    print('The columns in the experiment file DO NOT MATCH')


# maybe to make this something more like "COLUMNS GOOD - LIBRARY" and "COLUMNS BAD - EXPERIMENT"

Already up to date.
The columns in the library file match
The columns in the experiment file match

#### view files

In [24]:
library_git_plus_new = pd.concat([git_library, library_to_add], ignore_index = True, sort = False)
old_length = git_library.shape[0]
start = old_length - 2
end = old_length + 5
view_lib = library_git_plus_new.iloc[start:end]
view_lib

,#libraryId,experimentId,platform,SRSId,anatId,anatName,stageId,stageName,url_GSM,infoOrgan,infoStage,anatAnnotationStatus,anatBiologicalStatus,stageAnnotationStatus,sex,strain,genotype,speciesId,protocol,protocolType,RNASelection,globin_reduction,replicate,lib_name,sampleName,sampleAge_value,sampleAge_unit,PATOid,PATOname,EFOid,EFOname,comment,condition,physiologicalStatus,annotatorId,lastModificationDate
53437,SRX5123346,SRP173225,Illumina HiSeq 2000,SRS4136661,UBERON:0002298,brainstem,UBERON:0000112,sexually immature stage,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,brainstem,approx. 25 days old,perfect match,not documented,other,NA,,,10047,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,mC_2-RNAseq,"SAMN10564448,GSM3506932",25,day,,,,,PMID: 31906004,,,SAC,2026-02-02
53438,SRX5123345,SRP173225,Illumina HiSeq 2000,SRS4136660,UBERON:0002298,brainstem,UBERON:0000112,sexually immature stage,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,brainstem,approx. 25 days old,perfect match,not documented,other,NA,,,10047,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,mC_1-RNAseq,"SAMN10564451,GSM3506931",25,day,,,,,PMID: 31906004,,,SAC,2026-02-02
53439,SRX14497495,SRP115009,NextSeq 2000,SRS12295831,UBERON:0000468,multicellular organism,UBERON:0018241,prime adult stage,,"liver, kidney, testis",3.5 months,other,not documented,other,M,,,10047,,,polyA,,1,TT.TT164.6M,SAMN26787832,3.5,month,,,,,TT.TT164.6M,,,SAC,2026-02-02
53440,SRX14497506,SRP115009,NextSeq 2000,SRS12295831,UBERON:0000468,multicellular organism,UBERON:0018241,prime adult stage,,"liver, kidney, testis",3.5 months,other,not documented,other,M,,,10047,,,polyA,,1,TT.TT164.6M,SAMN26787832,3.5,month,,,,,TT.TT164.6M,,,SAC,2026-02-02
53441,SRX14497513,SRP115009,NextSeq 2000,SRS12295833,UBERON:0000468,multicellular organism,UBERON:0018241,prime adult stage,,"liver, kidney, testis",3.5 months,other,not documented,other,M,,,10047,,,polyA,,2,TE.TT1.4M,SAMN26787833,3.5,month,,,,,Bangor,,,SAC,2026-02-02
53442,SRX14497514,SRP115009,NextSeq 2000,SRS12295833,UBERON:0000468,multicellular organism,UBERON:0018241,prime adult stage,,"liver, kidney, testis",3.5 months,other,not documented,other,M,,,10047,,,polyA,,2,TE.TT1.4M,SAMN26787833,3.5,month,,,,,Bangor,,,SAC,2026-02-02
53443,SRX14497518,SRP115009,NextSeq 2000,SRS12295835,UBERON:0000468,multicellular organism,UBERON:0018241,prime adult stage,,"liver, kidney, testis",6 months,other,not documented,other,M,,,10047,,,polyA,,3,TT.TT163.4M,SAMN26787834,6,month,,,,,Bangor,,,SAC,2026-02-02

In [25]:
experiment_git_plus_new = pd.concat([git_experiment, experiment_to_add], ignore_index = True, sort = False)
experiment_git_plus_new.tail(n=3)

,#experimentId,experimentName,experimentDescription,experimentSource,experimentStatus,projectTags,numberOfAnnotatedLibraries,protocol,protocolType,GSE,Bioproject,PMID,reference_url,DOI,xrefs,comment
1024,SRP167239,Transcriptome analysis of brainstem in gerbils...,Coxsackievirus A16 (CA16) is one of the major ...,SRA,partial,Bgee 1K,3,NEBNext Ultra RNA Library Prep Kit,full_length,GSE121971,PRJNA501869,31906004,https://pmc.ncbi.nlm.nih.gov/articles/PMC7019476/,10.3390/v12010046,,removed infected libraries. this experiment is...
1025,SRP173225,Transcriptome analysis of brainstem in gerbils...,Enterovirus 71 (EV71) is one of the major path...,SRA,partial,Bgee 1K,3,NEBNext Ultra RNA Library Prep Kit,full_length,GSE123550,PRJNA509196,31906004,https://pmc.ncbi.nlm.nih.gov/articles/PMC7019476/,10.3390/v12010046,,removed infected libraries. this experiment is...
1026,SRP115009,Sequencing and mapping the mongolian gerbil ge...,We are using a genetic cross and reduced-repre...,SRA,partial,Bgee 1K,6,,,,PRJNA397533,37183864,https://pmc.ncbi.nlm.nih.gov/articles/PMC10210...,10.1093/molbev/msad115,,partial because majority of libraries are not ...

### add annotations to git

In [26]:
! git pull

Already up to date.

In [27]:
library_git_plus_new.to_csv(git_library_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
experiment_git_plus_new.to_csv(git_experiment_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
update_format(git_library_path)
update_format(git_experiment_path)

In [28]:
! git status

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../../RNA_Seq/RNASeqExperiment.tsv
	modified:   ../../../RNA_Seq/RNASeqLibrary.tsv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./
	../../scRNA/SRP589760/

no changes added to commit (use "git add" and/or "git commit -a")

In [29]:
! git add $git_experiment_path $git_library_path

In [30]:
! git commit -m $commit_message_exp

[develop 0da3df4] adding annotated bulk experiment SRP115009
 2 files changed, 7 insertions(+)

In [31]:
! git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.91 KiB | 1.91 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.sib.swiss/Bgee/expression-annotations/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.sib.swiss/Bgee/expression-annotations.git/
   10214f9..0da3df4  develop -> develop

### add annotation folder and script to git

In [ ]:
! git pull

1. run first two cells (annotation summary)
2. export as html

In [ ]:
! git add $path_to_output

In [ ]:
! git commit -m $commit_message_py

In [ ]:
! git push