## SRP492032

**paper:** cannot find one

**date, curator:** 2026-02-05, Sara Carsanaro

**notes**
* ferrets are 4 months old - sexually immature, weaned - juvenile stage
* guinea pigs are 6 weeks old - sexually immature, weaned - juvenile stage
* SRA experiment: NEBNext Poly(A) mRNA kit + NEBNext RNA First Strand and Ultra Directional RNA Second Strand Synthesis Modules

### annotation summary

In [21]:
anat_summary = library_to_add[['infoOrgan', 'anatId', 'anatName', 'anatAnnotationStatus']]
unique_anat = anat_summary.drop_duplicates()
display_df(unique_anat)

In [22]:
dev_summary = library_to_add[['infoStage', 'stageId', 'stageName', 'stageAnnotationStatus']]
unique_dev = dev_summary.drop_duplicates()
display_df(unique_dev)

### set variables, import packages, define functions

In [1]:
experiment_id = "SRP492032"

path_to_create_exp_script = "/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py" 
experiment_type = "bulk"

path_to_output_main = "/Users/scarsana/Desktop/git/expression-annotations/Notebooks/bulk/" 
path_to_output = "{}{}/".format(path_to_output_main, experiment_id)
library_path_from_script = "{}RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_path_from_script = "{}RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
library_to_add_path = "{}complete_RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_to_add_path = "{}complete_RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
script_file = "{}.ipynb".format(experiment_id)
commit_message_exp = '"adding annotated bulk experiment {}"'.format(experiment_id)
commit_message_py = '"adding annotation files for {} to notebook folder"'.format(experiment_id)


## to add to git
path_to_git_annotations = "/Users/scarsana/Desktop/git/expression-annotations/RNA_Seq/"
git_library_path = "{}RNASeqLibrary.tsv".format(path_to_git_annotations)
git_experiment_path = "{}RNASeqExperiment.tsv".format(path_to_git_annotations)

library_cols = ['#libraryId', 'experimentId', 'platform', 'SRSId', 'anatId', 'anatName', 'stageId', 'stageName', 'url_GSM', 'infoOrgan', 'infoStage', 'anatAnnotationStatus', 'anatBiologicalStatus', 'stageAnnotationStatus', 'sex', 'strain', 'genotype', 'speciesId', 'protocol', 'protocolType', 'RNASelection', 'globin_reduction', 'replicate', 'lib_name', 'sampleName', 'sampleAge_value', 'sampleAge_unit', 'PATOid', 'PATOname','EFOid', 'EFOname','comment', 'condition', 'physiologicalStatus', 'annotatorId', 'lastModificationDate']

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import os
import csv

# displays df with the scrollbar next to the DataFrame
def display_df(df):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    display(HTML("<div style='height: 300px; overflow: auto; width: fit-content'>" +
        df.style.to_html(index=False) + "</div>"))

# function that compares two columns in a dataframe and tells you which ones are not equal (case insensitive)
def compare_columns(df, col1, col2, return_col):
    compare_return = df[col1].str.lower() != df[col2].str.lower()  
    df.loc[compare_return, return_col] 
    if not any(compare_return):
        print("The two columns are equal (case insensitive)")
    else:
        print("The following rows are not equal: ")
        print(df.loc[compare_return, return_col])

# fixes formatting of file to match libreoffice settings/historic file format
def update_format(path):
    with open(path, 'r') as file:
        filedata = file.read()
    # Replace the target string
    filedata = filedata.replace("\t\"\"", "\t")
    # Write the file out again
    with open(path, 'w') as file:
        file.write(filedata)

# checks for duplicate values in a specific column and prints those values + the corresponding library id
def dup_check(df, column):
    duplicateCheck = df.duplicated(subset=[column], keep=False)
    duplicateCheck.sort_values(inplace=True)
    if duplicateCheck.unique().any() == False:
        print("no duplicate values in " + column)
    elif duplicateCheck.unique().any() == True and column != '#libraryId':
        dups = df[duplicateCheck].loc[:,['#libraryId', column]]
        df_dups = pd.DataFrame(dups)
        df_dups.sort_values(inplace=True, by=column)
        print(df_dups)
    elif duplicateCheck.unique().any() == True and column == '#libraryId':
        print(df[duplicateCheck].loc[:,['#libraryId']])

# prints all unique values in a specific column
def unique_sorted(df, column):
    unique = df[column].unique()
    unique.sort()
    print(unique)

### script

In [3]:
! python3 $path_to_create_exp_script $experiment_id $path_to_output $experiment_type

/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:120: SyntaxWarning: invalid escape sequence '\('
  all_protoc = [w.replace('(', '\(') for w in all_protoc]
/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:121: SyntaxWarning: invalid escape sequence '\)'
  all_protoc = [w.replace(')', '\)') for w in all_protoc]
Be patient, it may take a few minutes.
100%|█████████████████████████████████████████| 132/132 [02:15<00:00,  1.02s/it]
0 samples dont have attributes, try to find them somewhere else
0it [00:00, ?it/s]
0 samples dont have attributes
Fetching RunIds and ReadHashes for each library...can take several minutes
⚠️ Failed to fetch ReadHash for SRX23764972: Command 'esearch -db sra -query SRX23764972 | efetch -format runinfo' returned non-zero exit status 1.

### library annnotations

In [4]:
library = pd.read_csv(library_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(library)

#### anatomical entity
* [uberon ols](https://www.ebi.ac.uk/ols4/ontologies/uberon)

In [5]:
unique_sorted(library, "infoOrgan")

['blood' 'lung' 'nasal turbinate' 'trachea']

In [6]:
# blood
library.loc[library["infoOrgan"] == "blood", "anatId"] = "UBERON:0000178"
library.loc[library["infoOrgan"] == "blood", "anatName"] = "blood"
# perfect match, missing child term, other
library.loc[library["infoOrgan"] == "blood", "anatAnnotationStatus"] = "perfect match"
# full sampling, partial sampling, not documented
library.loc[library["infoOrgan"] == "blood", "anatBiologicalStatus"] = "not documented"

# lung
library.loc[library["infoOrgan"] == "lung", "anatId"] = "UBERON:0002048"
library.loc[library["infoOrgan"] == "lung", "anatName"] = "lung"
# perfect match, missing child term, other
library.loc[library["infoOrgan"] == "lung", "anatAnnotationStatus"] = "perfect match"
# full sampling, partial sampling, not documented
library.loc[library["infoOrgan"] == "lung", "anatBiologicalStatus"] = "not documented"


# nasal turbinate
library.loc[library["infoOrgan"] == "nasal turbinate", "anatId"] = "UBERON:0035612"
library.loc[library["infoOrgan"] == "nasal turbinate", "anatName"] = "nasal turbinal"
# perfect match, missing child term, other
library.loc[library["infoOrgan"] == "nasal turbinate", "anatAnnotationStatus"] = "perfect match"
# full sampling, partial sampling, not documented
library.loc[library["infoOrgan"] == "nasal turbinate", "anatBiologicalStatus"] = "not documented"


# trachea
library.loc[library["infoOrgan"] == "trachea", "anatId"] = "UBERON:0003126"
library.loc[library["infoOrgan"] == "trachea", "anatName"] = "trachea"
# perfect match, missing child term, other
library.loc[library["infoOrgan"] == "trachea", "anatAnnotationStatus"] = "perfect match"
# full sampling, partial sampling, not documented
library.loc[library["infoOrgan"] == "trachea", "anatBiologicalStatus"] = "not documented"


# view
display_df(library)

#### stage
- [species specific developmental ontologies](https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/ontology/components)

In [7]:
unique_sorted(library, "infoStage")

['4 months' '6 weeks']

In [8]:
# all
library.loc[:,'stageId'] = 'UBERON:0034919'
library.loc[:,'stageName'] = 'juvenile stage'
# perfect match, missing child term, other
library.loc[:,'stageAnnotationStatus'] = 'perfect match'



# view
display_df(library)

#### sex, strain, genotype, speciesId
- uniprot [strain list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/strains)
- uniprot [species list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/speclist)
- bgee [strain mapping](https://gitlab.sib.swiss/Bgee/expression-annotations/-/tree/develop/Strains?ref_type=heads)

In [ ]:
#library.loc[:,'sex'] = ''
#library.loc[library["sex"] == "male", "sex"] = "M"
#library.loc[library["sex"] == "female", "sex"] = "F"

#library.loc[:,'strain'] = ''

#library.loc[:,'genotype'] = ''

#library.loc[:,'speciesId'] = ''

# view
display_df(library)

#### protocol
see [bulk kits](https://gitlab.sib.swiss/Bgee/scRNA-Seq/-/blob/main/scripts/bulk_kits.csv) for some common protocols

In [9]:
# making these variables because we use them again in the experiment file
my_protocol = 'NEBNext Ultra Directional RNA Library Prep Kit'
# full_length or 3'
my_protocolType = 'full_length'

library.loc[:,'protocol'] = my_protocol
library.loc[:,'protocolType'] = my_protocolType
# polyA, ribo-minus, miRNA, lncRNA, circRNA
library.loc[:,'RNASelection'] = 'polyA'

# view
display_df(library)

#### globin, replicates

In [10]:
# check for duplicate SRSId values
dup_check(library, "SRSId")

no duplicate values in SRSId

In [ ]:
#library.loc[:,'globin_reduction'] = 'Y'

# replicates
#library.loc[library["#libraryId"] == "old", "replicate"] = "1"
#library.loc[library["#libraryId"].isin(["one", "two"]), "replicate"] = "1"

# view
display_df(library)

#### sample age, pato, physiological status
* [PATO](https://www.ebi.ac.uk/ols4/ontologies/pato)
* [EFO](https://www.ebi.ac.uk/ols4/ontologies/efo)

In [ ]:
#library.loc[:,'sampleAge_value'] = ''
#library.loc[:,'sampleAge_unit'] = ''

# ex. castrated male
#library.loc[:,'PATOid'] = ''
#library.loc[:,'PATOname'] = ''

# ex. castrated, pregnant, pre-smoltification, post-smoltification, laying eggs
#library.loc[:,'physiologicalStatus'] = ''

# ex. left, right
#library.loc[:,'EFOid'] = ''
#library.loc[:,'EFOname'] = ''

# view
display_df(library)

#### condition

In [ ]:
# ex. control, diet, light, reproductive capacity, time post mortem, time post feeding, 
# exercise details, menstruation, personality, litter size 
#library.loc[library["condition"] == "old", "condition"] = "new"

# view
display_df(library)

#### annotator id, last modification date

In [11]:
library.loc[:,'annotatorId'] = 'SAC'
library.loc[:,'lastModificationDate'] = '2026-02-05'

# view
display_df(library)

#### comments

In [12]:
library.loc[:,'comment'] = 'could not find paper but SRA has a lot of information'

#### save complete file with correct columns

In [13]:
library_file_complete = library[library_cols]
library_file_complete.to_csv(library_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

# view
display_df(library_file_complete)

### experiment annotations

In [14]:
experiment = pd.read_csv(experiment_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(experiment)

#### experiment and protocol details

In [15]:
# this will give you the number of rows in the complete library file 
# this should be the number of annotated libraries
ann_lib = len(library_file_complete.index)
len(library_file_complete.index)

30

In [16]:
# partial or total
experiment.loc[:,'experimentStatus'] = 'partial'
# Bgee 1K
experiment.loc[:,'projectTags'] = 'Bgee 1K' 
# see above cell, also can add as free text
experiment.loc[:,'numberOfAnnotatedLibraries'] = ann_lib

# these variables should already exist from above but if not can just add as free text
experiment.loc[:,'protocol'] = my_protocol
experiment.loc[:,'protocolType'] = my_protocolType

display_df(experiment)

#### paper and xrefs

In [17]:
#experiment.loc[:,'GSE'] = ''
#experiment.loc[:,'Bioproject'] = '' 
#experiment.loc[:,'PMID'] = ''
#experiment.loc[:,'reference_url'] = ''
experiment.loc[:,'DOI'] = ''
#experiment.loc[:,'xrefs'] = ''

display_df(experiment)

#### comments

In [18]:
experiment.loc[:,'comment'] = 'could not find paper but SRA has a lot of information, removed infected libraries and only included PBS control'

display_df(experiment)

#### save complete file

In [19]:
experiment.to_csv(experiment_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

### QA time

In [20]:
library_to_add = pd.read_csv(library_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
experiment_to_add = pd.read_csv(experiment_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

#### to add things here

#### check columns match

In [23]:
# pull from git and pull in library/experiment file
! git pull
git_library = pd.read_csv(git_library_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
git_experiment = pd.read_csv(git_experiment_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

# library file
if set(library_to_add.columns) == set(git_library.columns):
    print('The columns in the library file match')
else:
    print('The columns in the library file DO NOT MATCH')

# experiment file
if set(experiment_to_add.columns) == set(git_experiment.columns):
    print('The columns in the experiment file match')
else:
    print('The columns in the experiment file DO NOT MATCH')


# maybe to make this something more like "COLUMNS GOOD - LIBRARY" and "COLUMNS BAD - EXPERIMENT"

Already up to date.
The columns in the library file match
The columns in the experiment file match

#### view files

In [24]:
library_git_plus_new = pd.concat([git_library, library_to_add], ignore_index = True, sort = False)
old_length = git_library.shape[0]
start = old_length - 2
end = old_length + 5
view_lib = library_git_plus_new.iloc[start:end]
view_lib

,#libraryId,experimentId,platform,SRSId,anatId,anatName,stageId,stageName,url_GSM,infoOrgan,infoStage,anatAnnotationStatus,anatBiologicalStatus,stageAnnotationStatus,sex,strain,genotype,speciesId,protocol,protocolType,RNASelection,globin_reduction,replicate,lib_name,sampleName,sampleAge_value,sampleAge_unit,PATOid,PATOname,EFOid,EFOname,comment,condition,physiologicalStatus,annotatorId,lastModificationDate
53869,SRX24306522,SRP502712,Illumina NovaSeq 6000,SRS21069296,UBERON:0000945,stomach,UBERON:0000113,post-juvenile adult stage,,stomach,adult,perfect match,not documented,perfect match,F,,,9669,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,AFW3,SAMN40936849,,,,,,,PMID: 38929414,,,SAC,2026-02-05
53870,SRX24306523,SRP502712,Illumina NovaSeq 6000,SRS21069297,UBERON:0000945,stomach,UBERON:0018685,nursing stage,,stomach,suckling,perfect match,not documented,perfect match,M,,,9669,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,SFW1,SAMN40936874,,,,,,,PMID: 38929414,,,SAC,2026-02-05
53871,SRX23765065,SRP492032,Illumina HiSeq 4000,SRS20590719,UBERON:0002048,lung,UBERON:0034919,juvenile stage,,lung,6 weeks,perfect match,not documented,perfect match,F,,,10141,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,GP5MockGP2-LU,SAMN40168284,6,week,,,,,could not find paper but SRA has a lot of info...,"Phosphate-buffered saline (PBS), 300 L",,SAC,2026-02-05
53872,SRX23765059,SRP492032,Illumina HiSeq 4000,SRS20590713,UBERON:0002048,lung,UBERON:0034919,juvenile stage,,lung,6 weeks,perfect match,not documented,perfect match,F,,,10141,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,GP5MockGP1-LU,SAMN40168282,6,week,,,,,could not find paper but SRA has a lot of info...,"Phosphate-buffered saline (PBS), 300 L",,SAC,2026-02-05
53873,SRX23765040,SRP492032,Illumina HiSeq 4000,SRS20590696,UBERON:0003126,trachea,UBERON:0034919,juvenile stage,,trachea,6 weeks,perfect match,not documented,perfect match,F,,,10141,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,MockGP3TR,SAMN40168407,6,week,,,,,could not find paper but SRA has a lot of info...,"Phosphate-buffered saline (PBS), 300 L",,SAC,2026-02-05
53874,SRX23765039,SRP492032,Illumina HiSeq 4000,SRS20591444,UBERON:0035612,nasal turbinal,UBERON:0034919,juvenile stage,,nasal turbinate,6 weeks,perfect match,not documented,perfect match,F,,,10141,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,MockGP3NT,SAMN40168406,6,week,,,,,could not find paper but SRA has a lot of info...,"Phosphate-buffered saline (PBS), 300 L",,SAC,2026-02-05
53875,SRX23765037,SRP492032,Illumina HiSeq 4000,SRS20592755,UBERON:0002048,lung,UBERON:0034919,juvenile stage,,lung,6 weeks,perfect match,not documented,perfect match,F,,,10141,NEBNext Ultra Directional RNA Library Prep Kit,full_length,polyA,,,MockGP3LU,SAMN40168405,6,week,,,,,could not find paper but SRA has a lot of info...,"Phosphate-buffered saline (PBS), 300 L",,SAC,2026-02-05

In [25]:
experiment_git_plus_new = pd.concat([git_experiment, experiment_to_add], ignore_index = True, sort = False)
experiment_git_plus_new.tail(n=3)

,#experimentId,experimentName,experimentDescription,experimentSource,experimentStatus,projectTags,numberOfAnnotatedLibraries,protocol,protocolType,GSE,Bioproject,PMID,reference_url,DOI,xrefs,comment
1034,SRP583535,"Inflammatory, transcriptomic and cell fate res...",Airborne transmissibility of avian influenza v...,SRA,partial,Bgee 1K,4,TruSeq Stranded mRNA,full_length,,PRJNA1259901,40778772,https://pmc.ncbi.nlm.nih.gov/articles/PMC12456...,10.1128/jvi.00647-25,,removed infected libraries
1035,SRP502712,Whole transcriptome data of stomach tissues fr...,nutrient utilization of the red panda,SRA,total,Bgee 1K,24,NEBNext Ultra Directional RNA Library Prep Kit...,full_length,,PRJNA1098497,38929414,https://pmc.ncbi.nlm.nih.gov/articles/PMC11200...,10.3390/ani14121795,,
1036,SRP492032,Transcriptomic responses to influenza A virus ...,Ferrets and guinea pigs are both used to model...,SRA,partial,Bgee 1K,30,NEBNext Ultra Directional RNA Library Prep Kit,full_length,,PRJNA1081400,,,,,could not find paper but SRA has a lot of info...

### add annotations to git

In [26]:
! git pull

Already up to date.

In [27]:
library_git_plus_new.to_csv(git_library_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
experiment_git_plus_new.to_csv(git_experiment_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
update_format(git_library_path)
update_format(git_experiment_path)

In [28]:
! git status

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../../RNA_Seq/RNASeqExperiment.tsv
	modified:   ../../../RNA_Seq/RNASeqLibrary.tsv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./
	../../scRNA/SRP589760/

no changes added to commit (use "git add" and/or "git commit -a")

In [29]:
! git add $git_experiment_path $git_library_path

In [30]:
! git commit -m $commit_message_exp

[develop 75304d9] adding annotated bulk experiment SRP492032
 2 files changed, 31 insertions(+)

In [31]:
! git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.98 KiB | 1018.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.sib.swiss/Bgee/expression-annotations/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.sib.swiss/Bgee/expression-annotations.git/
   35ee933..75304d9  develop -> develop

### add annotation folder and script to git

In [ ]:
! git pull

1. run first two cells (annotation summary)
2. export as html

In [ ]:
! git add $path_to_output

In [ ]:
! git commit -m $commit_message_py

In [ ]:
! git push