## SRP357733

**paper:** [PMID: 31605445](https://pubmed.ncbi.nlm.nih.gov/31605445/) - Hypothalamic transcriptome of tame and aggressive silver foxes (Vulpes vulpes) identifies gene expression differences shared across brain regions, 2020 

**date, curator:** 2026-01-29, Sara Carsanaro

**notes**

### annotation summary
run this after annotation is complete

In [23]:
anat_summary = library_to_add[['infoOrgan', 'anatId', 'anatName', 'anatAnnotationStatus']]
unique_anat = anat_summary.drop_duplicates()
display_df(unique_anat)

In [24]:
dev_summary = library_to_add[['infoStage', 'stageId', 'stageName', 'stageAnnotationStatus']]
unique_dev = dev_summary.drop_duplicates()
display_df(unique_dev)

### set variables, import packages, define functions

In [1]:
experiment_id = "SRP357733"

path_to_create_exp_script = "/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py" 
experiment_type = "bulk"

path_to_output_main = "/Users/scarsana/Desktop/git/expression-annotations/Notebooks/bulk/" 
path_to_output = "{}{}/".format(path_to_output_main, experiment_id)
library_path_from_script = "{}RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_path_from_script = "{}RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
library_to_add_path = "{}complete_RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_to_add_path = "{}complete_RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
script_file = "{}.ipynb".format(experiment_id)
commit_message_exp = '"adding annotated bulk experiment {}"'.format(experiment_id)
commit_message_py = '"adding annotation files for {} to notebook folder"'.format(experiment_id)


## to add to git
path_to_git_annotations = "/Users/scarsana/Desktop/git/expression-annotations/RNA_Seq/"
git_library_path = "{}RNASeqLibrary.tsv".format(path_to_git_annotations)
git_experiment_path = "{}RNASeqExperiment.tsv".format(path_to_git_annotations)

library_cols = ['#libraryId', 'experimentId', 'platform', 'SRSId', 'anatId', 'anatName', 'stageId', 'stageName', 'url_GSM', 'infoOrgan', 'infoStage', 'anatAnnotationStatus', 'anatBiologicalStatus', 'stageAnnotationStatus', 'sex', 'strain', 'genotype', 'speciesId', 'protocol', 'protocolType', 'RNASelection', 'globin_reduction', 'replicate', 'lib_name', 'sampleName', 'sampleAge_value', 'sampleAge_unit', 'PATOid', 'PATOname','EFOid', 'EFOname','comment', 'condition', 'physiologicalStatus', 'annotatorId', 'lastModificationDate']

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import os
import csv

# displays df with the scrollbar next to the DataFrame
def display_df(df):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    display(HTML("<div style='height: 300px; overflow: auto; width: fit-content'>" +
        df.style.to_html(index=False) + "</div>"))

# function that compares two columns in a dataframe and tells you which ones are not equal (case insensitive)
def compare_columns(df, col1, col2, return_col):
    compare_return = df[col1].str.lower() != df[col2].str.lower()  
    df.loc[compare_return, return_col] 
    if not any(compare_return):
        print("The two columns are equal (case insensitive)")
    else:
        print("The following rows are not equal: ")
        print(df.loc[compare_return, return_col])

# fixes formatting of file to match libreoffice settings/historic file format
def update_format(path):
    with open(path, 'r') as file:
        filedata = file.read()
    # Replace the target string
    filedata = filedata.replace("\t\"\"", "\t")
    # Write the file out again
    with open(path, 'w') as file:
        file.write(filedata)

# checks for duplicate values in a specific column and prints those values + the corresponding library id
def dup_check(df, column):
    duplicateCheck = df.duplicated(subset=[column], keep=False)
    duplicateCheck.sort_values(inplace=True)
    if duplicateCheck.unique().any() == False:
        print("no duplicate values in " + column)
    elif duplicateCheck.unique().any() == True and column != '#libraryId':
        dups = df[duplicateCheck].loc[:,['#libraryId', column]]
        df_dups = pd.DataFrame(dups)
        df_dups.sort_values(inplace=True, by=column)
        print(df_dups)
    elif duplicateCheck.unique().any() == True and column == '#libraryId':
        print(df[duplicateCheck].loc[:,['#libraryId']])

# prints all unique values in a specific column
def unique_sorted(df, column):
    unique = df[column].unique()
    unique.sort()
    print(unique)

### script

In [3]:
! python3 $path_to_create_exp_script $experiment_id $path_to_output $experiment_type

/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:120: SyntaxWarning: invalid escape sequence '\('
  all_protoc = [w.replace('(', '\(') for w in all_protoc]
/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:121: SyntaxWarning: invalid escape sequence '\)'
  all_protoc = [w.replace(')', '\)') for w in all_protoc]
Be patient, it may take a few minutes.
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:02 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=bioproject&id=802593&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:02 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db bioproject -id 802593 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:04 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=bioproject&id=802593&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:04 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db bioproject -id 802593 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:06 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=bioproject&id=802593&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:06 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db bioproject -id 802593 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
  0%|                                                    | 0/24 [00:00<?, ?it/s]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:11 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009271&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:11 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009271 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:13 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009271&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:13 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009271 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
  8%|███▋                                        | 2/24 [00:05<00:57,  2.62s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:17 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009269&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:17 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009269 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:19 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009269&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:19 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009269 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:21 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009269&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:21 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009269 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:23 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009269&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 12%|█████▌                                      | 3/24 [00:12<01:35,  4.54s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:24 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009268&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:23 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009268 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:26 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009268&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:25 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009268 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:28 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009268&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:27 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009268 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:30 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009268&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 17%|███████▎                                    | 4/24 [00:19<01:47,  5.37s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:30 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009267&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:30 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009267 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:32 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009267&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:32 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009267 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:34 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009267&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:34 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009267 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:36 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009267&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 21%|█████████▏                                  | 5/24 [00:26<01:50,  5.81s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:37 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009266&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:37 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009266 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:39 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009266&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:39 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009266 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:41 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009266&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:40 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009266 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:43 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009266&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 25%|███████████                                 | 6/24 [00:32<01:50,  6.11s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:44 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009265&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:43 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009265 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:46 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009265&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:45 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009265 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:48 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009265&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:47 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009265 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:50 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009265&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 29%|████████████▊                               | 7/24 [00:39<01:47,  6.33s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:51 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009264&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:50 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009264 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
 33%|██████████████▋                             | 8/24 [00:42<01:23,  5.25s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:53 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009263&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:53 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009263 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:55 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009263&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:40:55 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009263 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:40:58 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009263&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:40:57 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009263 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:41:00 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009263&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 38%|████████████████▌                           | 9/24 [00:49<01:27,  5.82s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:41:01 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009262&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:41:00 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009262 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:41:03 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009262&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 16:41:02 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX14009262 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 16:41:05 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX14009262&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 16:41:04 CET 2026 )

### library annnotations

In [4]:
library = pd.read_csv(library_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(library)

#### anatomical entity
* [uberon ols](https://www.ebi.ac.uk/ols4/ontologies/uberon)

In [5]:
unique_sorted(library, "infoOrgan")

['hypothalamus']

In [6]:

# all
library.loc[:,'anatId'] = 'UBERON:0001898'
library.loc[:,'anatName'] = 'hypothalamus'
# perfect match, missing child term, other
library.loc[:,'anatAnnotationStatus'] = 'perfect match'
# partial sampling, full sampling, not documented
library.loc[:,'anatBiologicalStatus'] = 'not documented'



# view
display_df(library)

#### stage
- [species specific developmental ontologies](https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/ontology/components)

In [7]:
unique_sorted(library, "infoStage")

['1.5 years']

In [8]:
# all
library.loc[:,'stageId'] = 'UBERON:0018241'
library.loc[:,'stageName'] = 'prime adult stage'
# perfect match, missing child term, other
library.loc[:,'stageAnnotationStatus'] = 'missing child term'

# view
display_df(library)

#### sex, strain, genotype, speciesId
- uniprot [strain list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/strains)
- uniprot [species list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/speclist)
- bgee [strain mapping](https://gitlab.sib.swiss/Bgee/expression-annotations/-/tree/develop/Strains?ref_type=heads)

In [9]:
#library.loc[:,'sex'] = ''
#library.loc[library["sex"] == "male", "sex"] = "M"
#library.loc[library["sex"] == "female", "sex"] = "F"

library.loc[:,'strain'] = 'Silver'

#library.loc[:,'genotype'] = ''

#library.loc[:,'speciesId'] = ''

# view
display_df(library)

#### protocol
see [bulk kits](https://gitlab.sib.swiss/Bgee/scRNA-Seq/-/blob/main/scripts/bulk_kits.csv) for some common protocols

In [10]:
# making these variables because we use them again in the experiment file
my_protocol = 'TruSeq Stranded mRNA'
# full_length or 3'
my_protocolType = 'full_length'

library.loc[:,'protocol'] = my_protocol
library.loc[:,'protocolType'] = my_protocolType
# polyA, ribo-minus, miRNA, lncRNA, circRNA
library.loc[:,'RNASelection'] = 'polyA'

# view
display_df(library)

#### globin, replicates

In [11]:
# check for duplicate SRSId values
dup_check(library, "SRSId")

no duplicate values in SRSId

In [ ]:
#library.loc[:,'globin_reduction'] = 'Y'

# replicates
#library.loc[library["#libraryId"] == "old", "replicate"] = "1"
#library.loc[library["#libraryId"].isin(["one", "two"]), "replicate"] = "1"

# view
display_df(library)

#### sample age, pato, physiological status
* [PATO](https://www.ebi.ac.uk/ols4/ontologies/pato)
* [EFO](https://www.ebi.ac.uk/ols4/ontologies/efo)

In [12]:
library.loc[:,'sampleAge_value'] = '1.5'
library.loc[:,'sampleAge_unit'] = 'year'

# ex. castrated male
#library.loc[:,'PATOid'] = ''
#library.loc[:,'PATOname'] = ''

# ex. castrated, pregnant, pre-smoltification, post-smoltification, laying eggs
#library.loc[:,'physiologicalStatus'] = ''

# ex. left, right
library.loc[:,'EFOid'] = 'EFO:0001659'
library.loc[:,'EFOname'] = 'right'

# view
display_df(library)

#### condition

In [ ]:
# ex. control, diet, light, reproductive capacity, time post mortem, time post feeding, 
# exercise details, menstruation, personality, litter size 
#library.loc[library["condition"] == "old", "condition"] = "new"

# view
display_df(library)

#### annotator id, last modification date

In [13]:
library.loc[:,'annotatorId'] = 'SAC'
library.loc[:,'lastModificationDate'] = '2026-01-28'

# view
display_df(library)

#### comments

In [14]:
library.loc[:,'comment'] = 'PMID: 31605445'

#### save complete file with correct columns

In [15]:
library_file_complete = library[library_cols]
library_file_complete.to_csv(library_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

# view
display_df(library_file_complete)

### experiment annotations

In [16]:
experiment = pd.read_csv(experiment_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(experiment)

#### experiment and protocol details

In [17]:
# this will give you the number of rows in the complete library file 
# this should be the number of annotated libraries
ann_lib = len(library_file_complete.index)
len(library_file_complete.index)

24

In [18]:
# partial or total
experiment.loc[:,'experimentStatus'] = 'total'
# Bgee 1K
experiment.loc[:,'projectTags'] = 'Bgee 1K' 
# see above cell, also can add as free text
experiment.loc[:,'numberOfAnnotatedLibraries'] = ann_lib

# these variables should already exist from above but if not can just add as free text
experiment.loc[:,'protocol'] = my_protocol
experiment.loc[:,'protocolType'] = my_protocolType

display_df(experiment)

#### paper and xrefs

In [19]:
#experiment.loc[:,'GSE'] = ''
#experiment.loc[:,'Bioproject'] = '' 
experiment.loc[:,'PMID'] = '31605445'
experiment.loc[:,'reference_url'] = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7385667/'
experiment.loc[:,'DOI'] = '10.1111/gbb.12614'
#experiment.loc[:,'xrefs'] = ''

display_df(experiment)

#### comments

In [ ]:
#experiment.loc[:,'comment'] = ''

display_df(experiment)

#### save complete file

In [20]:
experiment.to_csv(experiment_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

### QA time

In [21]:
library_to_add = pd.read_csv(library_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
experiment_to_add = pd.read_csv(experiment_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

#### to add things here

#### check columns match

In [22]:
# pull from git and pull in library/experiment file
! git pull
git_library = pd.read_csv(git_library_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
git_experiment = pd.read_csv(git_experiment_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

# library file
if set(library_to_add.columns) == set(git_library.columns):
    print('The columns in the library file match')
else:
    print('The columns in the library file DO NOT MATCH')

# experiment file
if set(experiment_to_add.columns) == set(git_experiment.columns):
    print('The columns in the experiment file match')
else:
    print('The columns in the experiment file DO NOT MATCH')


# maybe to make this something more like "COLUMNS GOOD - LIBRARY" and "COLUMNS BAD - EXPERIMENT"

Already up to date.
The columns in the library file match
The columns in the experiment file match

#### view files

In [25]:
library_git_plus_new = pd.concat([git_library, library_to_add], ignore_index = True, sort = False)
old_length = git_library.shape[0]
start = old_length - 2
end = old_length + 5
view_lib = library_git_plus_new.iloc[start:end]
view_lib

,#libraryId,experimentId,platform,SRSId,anatId,anatName,stageId,stageName,url_GSM,infoOrgan,infoStage,anatAnnotationStatus,anatBiologicalStatus,stageAnnotationStatus,sex,strain,genotype,speciesId,protocol,protocolType,RNASelection,globin_reduction,replicate,lib_name,sampleName,sampleAge_value,sampleAge_unit,PATOid,PATOname,EFOid,EFOname,comment,condition,physiologicalStatus,annotatorId,lastModificationDate
53354,SRX17176869,SRP393425,Illumina HiSeq 2500,SRS14746988,UBERON:0002369,adrenal gland,UBERON:0018241,prime adult stage,,adrenal,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_53_113,SAMN30446308,1.5,year,,,EFO:0001659,right,methods mention 24 samples but only 4 are incl...,Aggressvie,,SAC,2026-01-28
53355,SRX17176868,SRP393425,Illumina HiSeq 2500,SRS14746987,UBERON:0002369,adrenal gland,UBERON:0018241,prime adult stage,,adrenal,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_52_112,SAMN30446307,1.5,year,,,EFO:0001659,right,methods mention 24 samples but only 4 are incl...,Aggressvie,,SAC,2026-01-28
53356,SRX14009271,SRP357733,Illumina HiSeq 2500,SRS11847136,UBERON:0001898,hypothalamus,UBERON:0018241,prime adult stage,,hypothalamus,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_58_178,SAMN25558286,1.5,year,,,EFO:0001659,right,PMID: 31605445,aggressive,,SAC,2026-01-28
53357,SRX14009270,SRP357733,Illumina HiSeq 2500,SRS11847135,UBERON:0001898,hypothalamus,UBERON:0018241,prime adult stage,,hypothalamus,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_57_177,SAMN25558285,1.5,year,,,EFO:0001659,right,PMID: 31605445,aggressive,,SAC,2026-01-28
53358,SRX14009269,SRP357733,Illumina HiSeq 2500,SRS11847134,UBERON:0001898,hypothalamus,UBERON:0018241,prime adult stage,,hypothalamus,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_56_176,SAMN25558284,1.5,year,,,EFO:0001659,right,PMID: 31605445,aggressive,,SAC,2026-01-28
53359,SRX14009268,SRP357733,Illumina HiSeq 2500,SRS11847133,UBERON:0001898,hypothalamus,UBERON:0018241,prime adult stage,,hypothalamus,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_55_535,SAMN25558283,1.5,year,,,EFO:0001659,right,PMID: 31605445,aggressive,,SAC,2026-01-28
53360,SRX14009267,SRP357733,Illumina HiSeq 2500,SRS11847132,UBERON:0001898,hypothalamus,UBERON:0018241,prime adult stage,,hypothalamus,1.5 years,perfect match,not documented,missing child term,M,Silver,,9627,TruSeq Stranded mRNA,full_length,polyA,,,Aggr_54_174,SAMN25558282,1.5,year,,,EFO:0001659,right,PMID: 31605445,aggressive,,SAC,2026-01-28

In [26]:
experiment_git_plus_new = pd.concat([git_experiment, experiment_to_add], ignore_index = True, sort = False)
experiment_git_plus_new.tail(n=3)

,#experimentId,experimentName,experimentDescription,experimentSource,experimentStatus,projectTags,numberOfAnnotatedLibraries,protocol,protocolType,GSE,Bioproject,PMID,reference_url,DOI,xrefs,comment
1012,SRP430431,North-African fox genomes show signatures of r...,Elucidating the evolutionary process of animal...,SRA,partial,Bgee 1K,11,,full_length,,PRJNA951250,37308700,https://pmc.ncbi.nlm.nih.gov/articles/PMC10527...,10.1038/s41559-023-02094-w,,majority of libraries were WGS and therefore n...
1013,SRP393425,RNA-seq of tame and aggressive fox Adrenals,RNA-seq of tame and aggressive fox Hypothalamus,SRA,total,Bgee 1K,4,TruSeq Stranded mRNA,full_length,,PRJNA872183,,https://www.ideals.illinois.edu/items/103556,,,"no paper, however data is described in https:/..."
1014,SRP357733,RNA-seq of tame and aggressive fox Hypothalamus,Gene expression study of tame and aggressive f...,SRA,total,Bgee 1K,24,TruSeq Stranded mRNA,full_length,,PRJNA802593,31605445,https://pmc.ncbi.nlm.nih.gov/articles/PMC7385667/,10.1111/gbb.12614,,

### add annotations to git

In [27]:
! git pull

Already up to date.

In [28]:
library_git_plus_new.to_csv(git_library_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
experiment_git_plus_new.to_csv(git_experiment_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
update_format(git_library_path)
update_format(git_experiment_path)

In [29]:
! git status

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../../RNA_Seq/RNASeqExperiment.tsv
	modified:   ../../../RNA_Seq/RNASeqLibrary.tsv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./

no changes added to commit (use "git add" and/or "git commit -a")

In [30]:
! git add $git_experiment_path $git_library_path

In [31]:
! git commit -m $commit_message_exp

[develop e49ccfa] adding annotated bulk experiment SRP357733
 2 files changed, 25 insertions(+)

In [32]:
! git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.10 KiB | 1.05 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.sib.swiss/Bgee/expression-annotations/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.sib.swiss/Bgee/expression-annotations.git/
   b867fcd..e49ccfa  develop -> develop

### add annotation folder and script to git

In [ ]:
! git pull

1. run first two cells (annotation summary)
2. export as html

In [ ]:
! git add $path_to_output

In [ ]:
! git commit -m $commit_message_py

In [ ]:
! git push