## SRP264585

**paper:** [PMID: 34646484](https://pmc.ncbi.nlm.nih.gov/articles/PMC8495804/) - Comparative transcriptome provides insights into the selection adaptation between wild and farmed foxes, 2021

**date, curator:** 2026-01-29, Sara Carsanaro

**notes**
* methods do seem to sugest ribo-minus, but it's not explicit enough so i am going with polyA since it's safer
* mixed samples - annotated with multicellular organism but to review if material anatomical entity is more appropriate (or something else)

### annotation summary
run this after annotation is complete

In [22]:
anat_summary = library_to_add[['infoOrgan', 'anatId', 'anatName', 'anatAnnotationStatus']]
unique_anat = anat_summary.drop_duplicates()
display_df(unique_anat)

In [23]:
dev_summary = library_to_add[['infoStage', 'stageId', 'stageName', 'stageAnnotationStatus']]
unique_dev = dev_summary.drop_duplicates()
display_df(unique_dev)

### set variables, import packages, define functions

In [1]:
experiment_id = "SRP264585"

path_to_create_exp_script = "/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py" 
experiment_type = "bulk"

path_to_output_main = "/Users/scarsana/Desktop/git/expression-annotations/Notebooks/bulk/" 
path_to_output = "{}{}/".format(path_to_output_main, experiment_id)
library_path_from_script = "{}RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_path_from_script = "{}RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
library_to_add_path = "{}complete_RNASeqLibrary_{}.tsv".format(path_to_output, experiment_id)
experiment_to_add_path = "{}complete_RNASeqExperiment_{}.tsv".format(path_to_output, experiment_id)
script_file = "{}.ipynb".format(experiment_id)
commit_message_exp = '"adding annotated bulk experiment {}"'.format(experiment_id)
commit_message_py = '"adding annotation files for {} to notebook folder"'.format(experiment_id)


## to add to git
path_to_git_annotations = "/Users/scarsana/Desktop/git/expression-annotations/RNA_Seq/"
git_library_path = "{}RNASeqLibrary.tsv".format(path_to_git_annotations)
git_experiment_path = "{}RNASeqExperiment.tsv".format(path_to_git_annotations)

library_cols = ['#libraryId', 'experimentId', 'platform', 'SRSId', 'anatId', 'anatName', 'stageId', 'stageName', 'url_GSM', 'infoOrgan', 'infoStage', 'anatAnnotationStatus', 'anatBiologicalStatus', 'stageAnnotationStatus', 'sex', 'strain', 'genotype', 'speciesId', 'protocol', 'protocolType', 'RNASelection', 'globin_reduction', 'replicate', 'lib_name', 'sampleName', 'sampleAge_value', 'sampleAge_unit', 'PATOid', 'PATOname','EFOid', 'EFOname','comment', 'condition', 'physiologicalStatus', 'annotatorId', 'lastModificationDate']

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import os
import csv

# displays df with the scrollbar next to the DataFrame
def display_df(df):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    display(HTML("<div style='height: 300px; overflow: auto; width: fit-content'>" +
        df.style.to_html(index=False) + "</div>"))

# function that compares two columns in a dataframe and tells you which ones are not equal (case insensitive)
def compare_columns(df, col1, col2, return_col):
    compare_return = df[col1].str.lower() != df[col2].str.lower()  
    df.loc[compare_return, return_col] 
    if not any(compare_return):
        print("The two columns are equal (case insensitive)")
    else:
        print("The following rows are not equal: ")
        print(df.loc[compare_return, return_col])

# fixes formatting of file to match libreoffice settings/historic file format
def update_format(path):
    with open(path, 'r') as file:
        filedata = file.read()
    # Replace the target string
    filedata = filedata.replace("\t\"\"", "\t")
    # Write the file out again
    with open(path, 'w') as file:
        file.write(filedata)

# checks for duplicate values in a specific column and prints those values + the corresponding library id
def dup_check(df, column):
    duplicateCheck = df.duplicated(subset=[column], keep=False)
    duplicateCheck.sort_values(inplace=True)
    if duplicateCheck.unique().any() == False:
        print("no duplicate values in " + column)
    elif duplicateCheck.unique().any() == True and column != '#libraryId':
        dups = df[duplicateCheck].loc[:,['#libraryId', column]]
        df_dups = pd.DataFrame(dups)
        df_dups.sort_values(inplace=True, by=column)
        print(df_dups)
    elif duplicateCheck.unique().any() == True and column == '#libraryId':
        print(df[duplicateCheck].loc[:,['#libraryId']])

# prints all unique values in a specific column
def unique_sorted(df, column):
    unique = df[column].unique()
    unique.sort()
    print(unique)

### script

In [3]:
! python3 $path_to_create_exp_script $experiment_id $path_to_output $experiment_type

/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:120: SyntaxWarning: invalid escape sequence '\('
  all_protoc = [w.replace('(', '\(') for w in all_protoc]
/Users/scarsana/Desktop/git/scRNA-Seq/scripts/Create_ExpLib_tables.py:121: SyntaxWarning: invalid escape sequence '\)'
  all_protoc = [w.replace(')', '\)') for w in all_protoc]
Be patient, it may take a few minutes.
 20%|█████████                                    | 1/5 [00:00<00:03,  1.04it/s]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:20 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397079&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 17:27:20 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397079 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:22 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397079&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 17:27:21 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397079 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:24 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397079&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 17:27:23 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397079 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:26 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397079&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 60%|███████████████████████████                  | 3/5 [00:08<00:05,  2.77s/it]curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:28 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397077&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 17:27:27 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397077 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
SECOND ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:29 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397077&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 WARNING:  FAILURE ( Wed Jan 28 17:27:29 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397077 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
LAST ATTEMPT
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:31 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397077&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
 ERROR:  FAILURE ( Wed Jan 28 17:27:31 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ efetch.fcgi -db SRA -id SRX8397077 -rettype full -retmode xml -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
EMPTY RESULT
QUERY FAILURE
curl: (22) The requested URL returned error: 400
>78 ERROR: >78 curl command failed ( Wed Jan 28 17:27:33 CET 2026 ) with: 22>78
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi -d db=SRA&id=SRX8397077&rettype=full&retmode=xml&tool=edirect&edirect=16.2&edirect_os=Darwin&email=scarsana%40SORGE42778>78
HTTP/1.1 400 Bad Request
100%|█████████████████████████████████████████████| 5/5 [00:16<00:00,  3.24s/it]
 WARNING:  FAILURE ( Wed Jan 28 17:27:36 CET 2026 )
nquire -url https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ elink.fcgi -id 10916120,10916119,10916118,10916117,10916116 -WebEnv MCID_697a38f7b121d86ee607871f -dbfrom sra -db biosample -cmd neighbor_history -linkname sra_biosample -tool edirect -edirect 16.2 -edirect_os Darwin -email scarsana@SORGE42778
<ERROR>Error calling ExLink server.</ERROR>
SECOND ATTEMPT
0 samples dont have attributes, try to find them somewhere else
0it [00:00, ?it/s]
0 samples dont have attributes
Fetching RunIds and ReadHashes for each library...can take several minutes

### library annnotations

In [4]:
library = pd.read_csv(library_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(library)

#### anatomical entity
* [uberon ols](https://www.ebi.ac.uk/ols4/ontologies/uberon)

In [5]:
unique_sorted(library, "infoOrgan")

['Brain, liver and kidney']

In [6]:

# all
library.loc[:,'anatId'] = 'UBERON:0000468'
library.loc[:,'anatName'] = 'multicellular organism'
# perfect match, missing child term, other
library.loc[:,'anatAnnotationStatus'] = 'other'
# partial sampling, full sampling, not documented
library.loc[:,'anatBiologicalStatus'] = 'not documented'

# view
display_df(library)

#### stage
- [species specific developmental ontologies](https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/ontology/components)

In [7]:
unique_sorted(library, "infoStage")

['adult']

In [8]:
# all
library.loc[:,'stageId'] = 'UBERON:0000113'
library.loc[:,'stageName'] = 'post-juvenile adult stage'
# perfect match, missing child term, other
library.loc[:,'stageAnnotationStatus'] = 'perfect match'

# view
display_df(library)

#### sex, strain, genotype, speciesId
- uniprot [strain list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/strains)
- uniprot [species list](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/speclist)
- bgee [strain mapping](https://gitlab.sib.swiss/Bgee/expression-annotations/-/tree/develop/Strains?ref_type=heads)

In [9]:
library.loc[:,'sex'] = 'NA'
#library.loc[library["sex"] == "male", "sex"] = "M"
#library.loc[library["sex"] == "female", "sex"] = "F"

#library.loc[:,'strain'] = ''

#library.loc[:,'genotype'] = ''

#library.loc[:,'speciesId'] = ''

# view
display_df(library)

#### protocol
see [bulk kits](https://gitlab.sib.swiss/Bgee/scRNA-Seq/-/blob/main/scripts/bulk_kits.csv) for some common protocols

In [10]:
# making these variables because we use them again in the experiment file
my_protocol = 'NEBNext Ultra RNA Library Prep Kit'
# full_length or 3'
my_protocolType = 'full_length'

library.loc[:,'protocol'] = my_protocol
library.loc[:,'protocolType'] = my_protocolType
# polyA, ribo-minus, miRNA, lncRNA, circRNA
library.loc[:,'RNASelection'] = 'polyA'

# view
display_df(library)

#### globin, replicates

In [11]:
# check for duplicate SRSId values
dup_check(library, "SRSId")

no duplicate values in SRSId

In [ ]:
#library.loc[:,'globin_reduction'] = 'Y'

# replicates
#library.loc[library["#libraryId"] == "old", "replicate"] = "1"
#library.loc[library["#libraryId"].isin(["one", "two"]), "replicate"] = "1"

# view
display_df(library)

#### sample age, pato, physiological status
* [PATO](https://www.ebi.ac.uk/ols4/ontologies/pato)
* [EFO](https://www.ebi.ac.uk/ols4/ontologies/efo)

In [ ]:
#library.loc[:,'sampleAge_value'] = ''
#library.loc[:,'sampleAge_unit'] = ''

# ex. castrated male
#library.loc[:,'PATOid'] = ''
#library.loc[:,'PATOname'] = ''

# ex. castrated, pregnant, pre-smoltification, post-smoltification, laying eggs
#library.loc[:,'physiologicalStatus'] = ''

# ex. left, right
#library.loc[:,'EFOid'] = ''
#library.loc[:,'EFOname'] = ''

# view
display_df(library)

#### condition

In [ ]:
# ex. control, diet, light, reproductive capacity, time post mortem, time post feeding, 
# exercise details, menstruation, personality, litter size 
#library.loc[library["condition"] == "old", "condition"] = "new"

# view
display_df(library)

#### annotator id, last modification date

In [12]:
library.loc[:,'annotatorId'] = 'SAC'
library.loc[:,'lastModificationDate'] = '2026-01-29'

# view
display_df(library)

#### comments

In [13]:
library.loc[:,'comment'] = 'mixed sample, possibly ribo-minus but paper is not clear enough so marking as polyA to be safe'

#### save complete file with correct columns

In [14]:
library_file_complete = library[library_cols]
library_file_complete.to_csv(library_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

# view
display_df(library_file_complete)

### experiment annotations

In [15]:
experiment = pd.read_csv(experiment_path_from_script, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
display_df(experiment)

#### experiment and protocol details

In [16]:
# this will give you the number of rows in the complete library file 
# this should be the number of annotated libraries
ann_lib = len(library_file_complete.index)
len(library_file_complete.index)

5

In [17]:
# partial or total
experiment.loc[:,'experimentStatus'] = 'total'
# Bgee 1K
experiment.loc[:,'projectTags'] = 'Bgee 1K' 
# see above cell, also can add as free text
experiment.loc[:,'numberOfAnnotatedLibraries'] = ann_lib

# these variables should already exist from above but if not can just add as free text
experiment.loc[:,'protocol'] = my_protocol
experiment.loc[:,'protocolType'] = my_protocolType

display_df(experiment)

#### paper and xrefs

In [18]:
#experiment.loc[:,'GSE'] = ''
#experiment.loc[:,'Bioproject'] = '' 
experiment.loc[:,'PMID'] = '34646484'
experiment.loc[:,'reference_url'] = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8495804/'
experiment.loc[:,'DOI'] = '10.1002/ece3.8071'
#experiment.loc[:,'xrefs'] = ''

display_df(experiment)

#### comments

In [19]:
experiment.loc[:,'comment'] = 'mixed sample, to review anatId after meeting'

display_df(experiment)

#### save complete file

In [20]:
experiment.to_csv(experiment_to_add_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)

### QA time

In [21]:
library_to_add = pd.read_csv(library_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
experiment_to_add = pd.read_csv(experiment_to_add_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

#### to add things here

#### check columns match

In [24]:
# pull from git and pull in library/experiment file
! git pull
git_library = pd.read_csv(git_library_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)
git_experiment = pd.read_csv(git_experiment_path, sep='\t', index_col=False, keep_default_na=False, na_values=['NULL','null', 'nan','NaN'], dtype=object)

# library file
if set(library_to_add.columns) == set(git_library.columns):
    print('The columns in the library file match')
else:
    print('The columns in the library file DO NOT MATCH')

# experiment file
if set(experiment_to_add.columns) == set(git_experiment.columns):
    print('The columns in the experiment file match')
else:
    print('The columns in the experiment file DO NOT MATCH')


# maybe to make this something more like "COLUMNS GOOD - LIBRARY" and "COLUMNS BAD - EXPERIMENT"

Already up to date.
The columns in the library file match
The columns in the experiment file match

#### view files

In [25]:
library_git_plus_new = pd.concat([git_library, library_to_add], ignore_index = True, sort = False)
old_length = git_library.shape[0]
start = old_length - 2
end = old_length + 5
view_lib = library_git_plus_new.iloc[start:end]
view_lib

,#libraryId,experimentId,platform,SRSId,anatId,anatName,stageId,stageName,url_GSM,infoOrgan,infoStage,anatAnnotationStatus,anatBiologicalStatus,stageAnnotationStatus,sex,strain,genotype,speciesId,protocol,protocolType,RNASelection,globin_reduction,replicate,lib_name,sampleName,sampleAge_value,sampleAge_unit,PATOid,PATOname,EFOid,EFOname,comment,condition,physiologicalStatus,annotatorId,lastModificationDate
53383,SRX16238364,SRP386394,Illumina NovaSeq 6000,SRS13879408,UBERON:0002107,liver,UBERON:0000113,post-juvenile adult stage,,liver,adult,perfect match,not documented,perfect match,M,montana,,9627,,,polyA,,,Model organism or animal sample from Vulpes vu...,SAMN29723075,,,,,,,"there is only one sample (SRSId) here, however...",,,SAC,2026-01-28
53384,SRX16238363,SRP386394,Illumina NovaSeq 6000,SRS13879408,UBERON:0000082,adult mammalian kidney,UBERON:0000113,post-juvenile adult stage,,kidney,adult,perfect match,not documented,perfect match,M,montana,,9627,,,polyA,,,Model organism or animal sample from Vulpes vu...,SAMN29723075,,,,,,,"there is only one sample (SRSId) here, however...",,,SAC,2026-01-28
53385,SRX8397080,SRP264585,Illumina HiSeq 2500,SRS6709921,UBERON:0000468,multicellular organism,UBERON:0000113,post-juvenile adult stage,,"Brain, liver and kidney",adult,other,not documented,perfect match,NA,Silver,,9627,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,Silver_fox_2,SAMN15015149,,,,,,,"mixed sample, possibly ribo-minus but paper is...",,,SAC,2026-01-29
53386,SRX8397079,SRP264585,Illumina HiSeq 2500,SRS6709920,UBERON:0000468,multicellular organism,UBERON:0000113,post-juvenile adult stage,,"Brain, liver and kidney",adult,other,not documented,perfect match,NA,Silver,,9627,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,Silver_fox_1,SAMN15015148,,,,,,,"mixed sample, possibly ribo-minus but paper is...",,,SAC,2026-01-29
53387,SRX8397078,SRP264585,Illumina HiSeq 2500,SRS6709919,UBERON:0000468,multicellular organism,UBERON:0000113,post-juvenile adult stage,,"Brain, liver and kidney",adult,other,not documented,perfect match,NA,,,494514,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,Blue_fox_3,SAMN15015147,,,,,,,"mixed sample, possibly ribo-minus but paper is...",,,SAC,2026-01-29
53388,SRX8397077,SRP264585,Illumina HiSeq 2500,SRS6709918,UBERON:0000468,multicellular organism,UBERON:0000113,post-juvenile adult stage,,"Brain, liver and kidney",adult,other,not documented,perfect match,NA,,,494514,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,Blue_fox_2,SAMN15015146,,,,,,,"mixed sample, possibly ribo-minus but paper is...",,,SAC,2026-01-29
53389,SRX8397076,SRP264585,Illumina HiSeq 2500,SRS6709917,UBERON:0000468,multicellular organism,UBERON:0000113,post-juvenile adult stage,,"Brain, liver and kidney",adult,other,not documented,perfect match,NA,,,494514,NEBNext Ultra RNA Library Prep Kit,full_length,polyA,,,Blue_fox_1,SAMN15015145,,,,,,,"mixed sample, possibly ribo-minus but paper is...",,,SAC,2026-01-29

In [26]:
experiment_git_plus_new = pd.concat([git_experiment, experiment_to_add], ignore_index = True, sort = False)
experiment_git_plus_new.tail(n=3)

,#experimentId,experimentName,experimentDescription,experimentSource,experimentStatus,projectTags,numberOfAnnotatedLibraries,protocol,protocolType,GSE,Bioproject,PMID,reference_url,DOI,xrefs,comment
1014,SRP357733,RNA-seq of tame and aggressive fox Hypothalamus,Gene expression study of tame and aggressive f...,SRA,total,Bgee 1K,24,TruSeq Stranded mRNA,full_length,,PRJNA802593,31605445,https://pmc.ncbi.nlm.nih.gov/articles/PMC7385667/,10.1111/gbb.12614,,
1015,SRP386394,Vulpes vulpes Raw sequence reads,Vulpes vulpes RNA-seq reads,SRA,total,Bgee 1K,5,,,,PRJNA858627,40681668,https://pmc.ncbi.nlm.nih.gov/articles/PMC12274...,10.1038/s42003-025-08450-9,,flagging for possible subspecies update - Vulp...
1016,SRP264585,vulpes transcriptome data,vulpes transcriptome data,SRA,total,Bgee 1K,5,NEBNext Ultra RNA Library Prep Kit,full_length,,PRJNA635008,34646484,https://pmc.ncbi.nlm.nih.gov/articles/PMC8495804/,10.1002/ece3.8071,,"mixed sample, to review anatId after meeting"

### add annotations to git

In [27]:
! git pull

Already up to date.

In [28]:
library_git_plus_new.to_csv(git_library_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
experiment_git_plus_new.to_csv(git_experiment_path, sep="\t", index=False, quoting=csv.QUOTE_ALL)
update_format(git_library_path)
update_format(git_experiment_path)

In [29]:
! git status

On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../../RNA_Seq/RNASeqExperiment.tsv
	modified:   ../../../RNA_Seq/RNASeqLibrary.tsv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./

no changes added to commit (use "git add" and/or "git commit -a")

In [30]:
! git add $git_experiment_path $git_library_path

In [31]:
! git commit -m $commit_message_exp

[develop 7ee35c0] adding annotated bulk experiment SRP264585
 2 files changed, 6 insertions(+)

In [32]:
! git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.81 KiB | 1.81 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.sib.swiss/Bgee/expression-annotations/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.sib.swiss/Bgee/expression-annotations.git/
   32f3b4e..7ee35c0  develop -> develop

### add annotation folder and script to git

In [ ]:
! git pull

1. run first two cells (annotation summary)
2. export as html

In [ ]:
! git add $path_to_output

In [ ]:
! git commit -m $commit_message_py

In [ ]:
! git push